/****************************************************************************

Copyright (c) 2010-2016 Qualcomm Technologies International, Ltd.
All Rights Reserved.
Qualcomm Technologies International, Ltd. Confidential and Proprietary.

REVISION:      $Revision: #2 $
****************************************************************************/


#include "csr_synergy.h"

#include "csr_bt_declare_tasks.h"

/* This file contains nothing but the global variables used to hold
 * the queue numbers. All these variables are _read_only_ */

/* Synergy Framework */
CsrSchedQid CSR_HCI_IFACEQUEUE;
CsrSchedQid CSR_TM_BLUECORE_IFACEQUEUE;
CsrSchedQid CSR_VM_IFACEQUEUE;
CsrSchedQid CSR_FP_IFACEQUEUE;
CsrSchedQid CSR_BCCMD_IFACEQUEUE;
#ifdef CSR_USE_QCA_CHIP
CsrSchedQid CSR_QVSC_IFACEQUEUE;
#endif
CsrSchedQid CSR_HQ_IFACEQUEUE;
CsrSchedQid CSR_AM_IFACEQUEUE;
#ifdef CSR_USE_DSPM
CsrSchedQid CSR_DSPM_IFACEQUEUE;
#endif
CsrSchedQid CSR_UI_IFACEQUEUE;
CsrSchedQid CSR_APP_IFACEQUEUE;

/* Synergy Bluetooth */
CsrSchedQid DM_IFACEQUEUE;
CsrSchedQid DM_ACLQUEUE;
CsrSchedQid DM_HCI_IFACEQUEUE;
CsrSchedQid L2CAP_IFACEQUEUE;
CsrSchedQid RFCOMM_IFACEQUEUE;
CsrSchedQid SDP_L2CAP_IFACEQUEUE;
CsrSchedQid SDP_IFACEQUEUE;
CsrSchedQid ATT_IFACEQUEUE;
CsrSchedQid CSR_BT_CM_IFACEQUEUE;
CsrSchedQid CSR_BT_SC_IFACEQUEUE;
CsrSchedQid CSR_BT_DG_IFACEQUEUE;
CsrSchedQid CSR_BT_AT_IFACEQUEUE;
CsrSchedQid CSR_BT_OPS_IFACEQUEUE;
CsrSchedQid CSR_BT_OPC_IFACEQUEUE;
CsrSchedQid CSR_BT_MAPC_IFACEQUEUE;
CsrSchedQid CSR_BT_MAPC_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_MAPS_IFACEQUEUE;
CsrSchedQid CSR_BT_MAPS_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_SYNCC_IFACEQUEUE;
CsrSchedQid CSR_BT_SYNCS_IFACEQUEUE;
CsrSchedQid CSR_BT_IWU_IFACEQUEUE;
CsrSchedQid CSR_BT_SPP_IFACEQUEUE;
CsrSchedQid CSR_BT_SPP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_GATT_IFACEQUEUE;
CsrSchedQid CSR_BT_GATT_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_HOGH_IFACEQUEUE;
CsrSchedQid CSR_BT_PROX_SRV_IFACEQUEUE;
CsrSchedQid CSR_BT_THERM_SRV_IFACEQUEUE;
CsrSchedQid CSR_BT_GNSS_CLIENT_IFACEQUEUE;
CsrSchedQid CSR_BT_GNSS_SERVER_IFACEQUEUE;
CsrSchedQid CSR_BT_ASM_IFACEQUEUE;

CsrSchedQid CSR_BT_HFG_IFACEQUEUE;
CsrSchedQid CSR_BT_HF_IFACEQUEUE;
CsrSchedQid CSR_BT_FTS_IFACEQUEUE;
CsrSchedQid CSR_BT_BNEP_IFACEQUEUE;
CsrSchedQid CSR_BT_BSL_IFACEQUEUE;
CsrSchedQid CSR_BT_IP_IFACEQUEUE;
CsrSchedQid CSR_BT_ICMP_IFACEQUEUE;
CsrSchedQid CSR_BT_UDP_IFACEQUEUE;
CsrSchedQid CSR_BT_DHCP_IFACEQUEUE;
CsrSchedQid CSR_BT_TFTP_IFACEQUEUE;
CsrSchedQid CSR_BT_CTRL_IFACEQUEUE;
CsrSchedQid CSR_BT_BIPC_IFACEQUEUE;
CsrSchedQid CSR_BT_FTC_IFACEQUEUE;
CsrSchedQid CSR_BT_PPP_IFACEQUEUE;
CsrSchedQid CSR_BT_BPPC_IFACEQUEUE;
CsrSchedQid CSR_BT_AV_IFACEQUEUE;
CsrSchedQid CSR_BT_AVRCP_IFACEQUEUE;
CsrSchedQid CSR_BT_SAPS_IFACEQUEUE;
CsrSchedQid CSR_BT_SAPC_IFACEQUEUE;
CsrSchedQid CSR_BT_SD_IFACEQUEUE;
CsrSchedQid CSR_BT_HIDH_IFACEQUEUE;
CsrSchedQid CSR_BT_BPPS_IFACEQUEUE;
CsrSchedQid CSR_BT_HCRP_IFACEQUEUE;
CsrSchedQid CSR_BT_BIPS_IFACEQUEUE;
CsrSchedQid CSR_BT_BIPS_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_SMLC_IFACEQUEUE;
CsrSchedQid CSR_BT_SMLS_IFACEQUEUE;
CsrSchedQid CSR_BT_DUNC_IFACEQUEUE;
CsrSchedQid CSR_BT_JSR82_IFACEQUEUE;
CsrSchedQid CSR_BT_HIDD_IFACEQUEUE;
CsrSchedQid CSR_BT_PAC_IFACEQUEUE;
CsrSchedQid CSR_BT_PAS_IFACEQUEUE;
CsrSchedQid CSR_BT_MCAP_IFACEQUEUE;
CsrSchedQid CSR_BT_HDP_IFACEQUEUE;
CsrSchedQid CSR_BT_AMPM_IFACEQUEUE;
CsrSchedQid CSR_BT_FAKEPAL_IFACEQUEUE;
CsrSchedQid CSR_BT_PHDC_AG_IFACEQUEUE;
CsrSchedQid CSR_BT_PHDC_MGR_IFACEQUEUE;
CsrSchedQid TESTQUEUE;
CsrSchedQid CSR_BT_EXTRA_IFACEQUEUE;
#ifdef CSR_BT_INSTALL_AVRCP_COVER_ART
CsrSchedQid CSR_BT_AVRCP_IMAGING_IFACEQUEUE;
#endif

/* Synergy WiFi */
CsrSchedQid CSR_WIFI_SME_IFACEQUEUE;
CsrSchedQid CSR_WIFI_ROUTER_IFACEQUEUE;
CsrSchedQid CSR_CRYPTO_IFACEQUEUE;
CsrSchedQid CSR_WIFI_PAL_DATA_IFACEQUEUE;
CsrSchedQid CSR_WIFI_NME_IFACEQUEUE;
CsrSchedQid CSR_IP_IFACEQUEUE;

/* Synergy BT Application queues */
CsrSchedQid CSR_BT_GAP_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_AV_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_AVRCP_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_SPP_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_SPP_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_HFG_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_HF_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_FTS_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_FTC_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_PHDC_AG_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_PHDC_MGR_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_AMPWIFI_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_GENERIC_SERVER_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_GENERIC_SERVER_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_LE_BROWSER_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_LE_BROWSER_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_THERMC_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_THERMC_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_THERMS_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_PROXC_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_PROXC_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_PROXS_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_RSCC_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_RSCC_APP_EXTRA_IFACEQUEUE;
CsrSchedQid CSR_BT_RSCS_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_HOGH_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_HOGD_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_GNSS_CLIENT_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_GNSS_SERVER_APP_IFACEQUEUE;

CsrSchedQid CSR_BT_PAN_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_MPAA_IFACEQUEUE;
CsrSchedQid CSR_BT_AUDIO_APP_IFACEQUEUE;
CsrSchedQid CSR_BT_PAC_APP_IFACEQUEUE;
