/**
 * dw9716_actuator.h
 *
 * DESCRIPTION
 *  Auto-Generated by Actuator tool.
 *
 * Copyright (c) 2014-2015 Qualcomm Technologies, Inc. All Rights Reserved.
 *   Qualcomm Technologies Proprietary and Confidential.
 */
  {
    .actuator_params =
    {
      .module_name = "abico",
      .actuator_name = "dw9714",
      .i2c_addr = 0x18,
      .i2c_data_type = CAMERA_I2C_BYTE_DATA,
      .i2c_addr_type = CAMERA_I2C_BYTE_ADDR,
      .act_type = ACTUATOR_TYPE_VCM,
      .data_size = 10,
      .reg_tbl =
      {
        .reg_tbl_size = 1,
        .reg_params =
        {
          {
            .reg_write_type = ACTUATOR_WRITE_DAC,
            .hw_mask = 0x0000000F,
            .reg_addr = 0xFFFF,
            .hw_shift = 0,
            .data_shift = 4,
          },
        },
      },
      .init_setting_size = 4,
      .init_settings =
      {
        {0xEC, CAMERA_I2C_BYTE_ADDR, 0xA3,
          CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0},
        {0xA1, CAMERA_I2C_BYTE_ADDR, 0x05,
          CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0},
        {0xF2, CAMERA_I2C_BYTE_ADDR, 0x08,
          CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0},
        {0xDC, CAMERA_I2C_BYTE_ADDR, 0x51,
          CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0},
      },
    }, /* actuator_params */

    .actuator_tuned_params =
    {
      .scenario_size =
      {
        2, /* MOVE_NEAR */
        3, /* MOVE_FAR */
      },
      .ringing_scenario =
      {
        /* MOVE_NEAR */
        {
          36,
          369,
        },
        /* MOVE_FAR */
        {
          72,
          198,
          369,
        },
      },
      .initial_code = 136,
      .region_size = 1,
      .region_params =
      {
        {
          .step_bound =
          {
            386, /* Macro step boundary*/
            0, /* Infinity step boundary*/
          },
          .code_per_step = 1,
        },
      },
      .damping =
      {
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 7000,
                .hw_params = 0x7,
              },
            },
          },
          /* Scenario 1 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 4500,
                .hw_params = 0x00000009,
              },
            },
          },
        },
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 4500,
                .hw_params = 0x0000007,
              },
            },
          },
          /* Scenario 1 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 12000,
                .hw_params = 0x0000000E,
              },
            },
          },
          /* Scenario 2 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 15000,
                .hw_params = 0x00000004,
              },
            },
          },
        },
      },
    }, /* actuator_tuned_params */
  },
