#! /bin/sh
#
# init.d script to start the adsprpc daemon
#

set -e

case "$1" in
  start)
        echo -n "Starting adsprpcd: "
        start-stop-daemon -c system -S -b -a /usr/bin/adsprpcd
        echo "done"
        ;;
  stop)
        echo -n "Stopping adsprpcd: "
        start-stop-daemon -c system -K -n adsprpcd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage adsprpcd { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

