#! /bin/sh
## Copyright (c) 2016 Qualcomm Technologies, Inc.
## All Rights Reserved.
## Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# init.d script to start the sdsprpc daemon
#

set -e

case "$1" in
  start)
        echo -n "Starting sdsprpcd: "
        start-stop-daemon -S -b -a /usr/bin/sdsprpcd
        echo "done"
        ;;
  stop)
        echo -n "Stopping sdsprpcd: "
        start-stop-daemon -K -n sdsprpcd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage sdsprpcd { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

