#! /bin/sh
## Copyright (c) 2016 Qualcomm Technologies, Inc.
## All Rights Reserved.
## Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# init.d script to start the adsprpc daemon
#

set -e

case "$1" in
  start)
        echo -n "Starting mdsprpcd: "
        start-stop-daemon -S -b -a /usr/bin/mdsprpcd
        echo "done"
        ;;
  stop)
        echo -n "Stopping mdsprpcd: "
        start-stop-daemon -K -n mdsprpcd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage mdsprpcd { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
