/**********************************************************************
* Copyright (c) 2013-2015 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
**********************************************************************/

/* NOTE : Autogenerated File with just Copyright Added.*/

#ifndef _ADSP_FD_H
#define _ADSP_FD_H
#include "AEEStdDef.h"
#ifndef __QAIC_HEADER
#define __QAIC_HEADER(ff) ff
#endif //__QAIC_HEADER

#ifndef __QAIC_HEADER_EXPORT
#define __QAIC_HEADER_EXPORT
#endif // __QAIC_HEADER_EXPORT

#ifndef __QAIC_HEADER_ATTRIBUTE
#define __QAIC_HEADER_ATTRIBUTE
#endif // __QAIC_HEADER_ATTRIBUTE

#ifndef __QAIC_IMPL
#define __QAIC_IMPL(ff) ff
#endif //__QAIC_IMPL

#ifndef __QAIC_IMPL_EXPORT
#define __QAIC_IMPL_EXPORT
#endif // __QAIC_IMPL_EXPORT

#ifndef __QAIC_IMPL_ATTRIBUTE
#define __QAIC_IMPL_ATTRIBUTE
#endif // __QAIC_IMPL_ATTRIBUTE
#ifdef __cplusplus
extern "C" {
#endif
typedef struct POINT1 POINT1;
struct POINT1 {
   int x;
   int y;
};
typedef struct FACEINFO1 FACEINFO1;
struct FACEINFO1 {
   int nID;
   POINT1 ptLeftTop;
   POINT1 ptRightTop;
   POINT1 ptLeftBottom;
   POINT1 ptRightBottom;
   int nPose;
   int nConfidence;
};
typedef struct RECT1 RECT1;
struct RECT1 {
   int left;
   int top;
   int right;
   int bottom;
};
#define POSE_TYPE_COUNT 3
typedef struct trackingAngle_t trackingAngle_t;
struct trackingAngle_t {
   int anNonTrackingAngle[3];
};
/**
       * Get version
       */
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_getVersion)(uint8* majorVersion, uint8* minorVersion) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_CreateDetection)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_CreateDtResult)(int nMaxFaceNumber, int nMaxSwapNumber) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_Detection)(int hDT, const uint8* pImage, int pImageLen, int nWidth, int nHeight, int nAccuracy, int hDtResult) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtFaceCount)(int hDtResult, int* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_DeleteDtResult)(int hDtResult) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_DeleteDetection)(int hDT) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtFaceInfo)(int hDtResult, int nIndex, FACEINFO1* psFaceInfo) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtStep)(int hDT, int nNonTrackingStep, int nTrackingStep) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtStep)(int hDT, int* pnNonTrackingStep, int* pnTrackingStep) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtAngle)(int hDT, const trackingAngle_t* anNonTrackingAngleStruct, int nTrackingAngleExtension) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtAngle)(int hDT, trackingAngle_t* panNonTrackingAngle, int* pnTrackingAngleExtension) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtDirectionMask)(int hDT, uint8 bMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtFaceSizeRange)(int hDT, int nMinSize, int nMaxSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtFaceSizeRange)(int hDT, int* pnMinSize, int* pnMaxSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtMode)(int hDT, int nMode) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtMode)(int hDT, int* pnMode) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtThreshold)(int hDT, int nNonTrackingThreshold, int nTrackingThreshold) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtThreshold)(int hDT, int* pnNonTrackingThreshold, int* pnTrackingThreshold) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetWMemoryArea)(uint8* pMemoryAddr, int pMemoryAddrLen) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetBMemoryArea)(uint8* pMemoryAddr, int pMemoryAddrLen) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_FreeWMemoryArea)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_FreeBMemoryArea)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtRequiredMovieMemSize)(int nWidth, int nHeight, int nMinSize, int nMaxFaceNumber, const RECT1* rcNonTrackingEdge, int nNonTrackingStep, const RECT1* rcTrackingEdge, int nTrackingStep, int* pnBackupMemSize, int* pnMinWorkMemSize, int* pnMaxWorkMemSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtRefreshCount)(int hDT, int nMode, int nRefreshCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtRefreshCount)(int hDT, int nMode, int* pnRefreshCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDSPPowerPref)(int clock, int bus, int latency, int b_absapi) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_DtLockID)(int hDtResult, int nID) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtLostParam)(int hDT, int nFaceRetryCount, int nHeadRetryCount, int nHoldCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtLostParam)(int hDT, int* pnFaceRetryCount, int* pnHeadRetryCount, int* pnHoldCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtRequiredStillMemSize)(int nWidth, int nHeight, int nMinSize, int nMaxFaceNumber, const RECT1* rcNonTrackingEdge, int nNonTrackingStep, int* pnBackupMemSize, int* pnMinWorkMemSize, int* pnMaxWorkMemSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_ClearDtResult)(int hDtResult) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtRectangleMask)(int hDT, const RECT1* rcNonTrackingArea, const RECT1* rcTrackingArea) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtRectangleMask)(int hDT, RECT1* prcNonTrackingArea, RECT1* prcTrackingArea) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtDirectionMask)(int hDT, uint8* pbMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtModifyMoveRate)(int hDT, int nModifyMoveRate) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtModifyMoveRate)(int hDT, int* pnModifyMoveRate) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtMemorySize)(int hDT, int unSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtMemorySize)(int hDT, int* punSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_SetDtTimeout)(int hDT, int nNonTrackingTimeout, int nTrackingTimeout) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT int __QAIC_HEADER(adsp_fd_GetDtTimeout)(int hDT, int* pnNonTrackingTimeout, int* pnTrackingTimeout) __QAIC_HEADER_ATTRIBUTE;
#ifdef __cplusplus
}
#endif
#endif //_ADSP_FD_H
