/**********************************************************************
* Copyright (c) 2013-2015 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
**********************************************************************/

/* NOTE : Autogenerated File with just Copyright Added.*/

#ifndef _ADSP_FD_STUB_H
#define _ADSP_FD_STUB_H
#include "adsp_fd.h"
#include "remote.h"
#ifndef ALLOCATOR_H
#define ALLOCATOR_H

#include <stdlib.h>
#include <stdint.h>

typedef struct _heap _heap;
struct _heap {
   _heap* pPrev;
   const char* loc;
   uint64_t buf;
};

typedef struct allocator {
   _heap* pheap;
   uint8_t* stack;
   uint8_t* stackEnd;
   int nSize;
} allocator;

static __inline int _heap_alloc(_heap** ppa, const char* loc, int size, void** ppbuf) {
   _heap* pn = 0;
   pn = malloc(size + sizeof(_heap) - sizeof(uint64_t));
   if(pn != 0) {
      pn->pPrev = *ppa;
      pn->loc = loc;
      *ppa = pn;
      *ppbuf = (void*)&(pn->buf);
      return 0;
   } else {
      return -1;
   }
}
#define _ALIGN_SIZE(x, y) (((x) + (y-1)) & ~(y-1))


static __inline int allocator_alloc(allocator* me,
                                    const char* loc,
                                    int size,
                                    unsigned int al,
                                    void** ppbuf) {
   if(size < 0) {
      return -1;
   } else if (size == 0) {
      *ppbuf = 0;
      return 0;
   }
   if((_ALIGN_SIZE((uintptr_t)me->stackEnd, al) + size) < (uintptr_t)me->stack + me->nSize) {
      *ppbuf = (uint8_t*)_ALIGN_SIZE((uintptr_t)me->stackEnd, al);
      me->stackEnd = (uint8_t*)_ALIGN_SIZE((uintptr_t)me->stackEnd, al) + size;
      return 0;
   } else {
      return _heap_alloc(&me->pheap, loc, size, ppbuf);
   }
}


static __inline void allocator_deinit(allocator* me) {
   _heap* pa = me->pheap;
   while(pa != 0) {
      _heap* pn = pa;
      const char* loc = pn->loc;
      (void)loc;
      pa = pn->pPrev;
      free(pn);
   }
}

static __inline void allocator_init(allocator* me, uint8_t* stack, int stackSize) {
   me->stack =  stack;
   me->stackEnd =  stack + stackSize;
   me->nSize = stackSize;
   me->pheap = 0;
}


#endif // ALLOCATOR_H

#ifndef SLIM_H
#define SLIM_H

#include <stdint.h>

//a C data structure for the idl types that can be used to implement
//static and dynamic language bindings fairly efficiently.
//
//the goal is to have a minimal ROM and RAM footprint and without
//doing too many allocations.  A good way to package these things seemed
//like the module boundary, so all the idls within  one module can share
//all the type references.


#define PARAMETER_IN       0x0
#define PARAMETER_OUT      0x1
#define PARAMETER_INOUT    0x2
#define PARAMETER_ROUT     0x3
#define PARAMETER_INROUT   0x4

//the types that we get from idl
#define TYPE_OBJECT             0x0
#define TYPE_INTERFACE          0x1
#define TYPE_PRIMITIVE          0x2
#define TYPE_ENUM               0x3
#define TYPE_STRING             0x4
#define TYPE_WSTRING            0x5
#define TYPE_STRUCTURE          0x6
#define TYPE_UNION              0x7
#define TYPE_ARRAY              0x8
#define TYPE_SEQUENCE           0x9

//these require the pack/unpack to recurse
//so it's a hint to those languages that can optimize in cases where
//recursion isn't necessary.
#define TYPE_COMPLEX_STRUCTURE  (0x10 | TYPE_STRUCTURE)
#define TYPE_COMPLEX_UNION      (0x10 | TYPE_UNION)
#define TYPE_COMPLEX_ARRAY      (0x10 | TYPE_ARRAY)
#define TYPE_COMPLEX_SEQUENCE   (0x10 | TYPE_SEQUENCE)


typedef struct Type Type;

#define INHERIT_TYPE\
   int32_t nativeSize;                /*in the simple case its the same as wire size and alignment*/\
   union {\
      struct {\
         const uintptr_t         p1;\
         const uintptr_t         p2;\
      } _cast;\
      struct {\
         uint32_t  iid;\
         uint32_t  bNotNil;\
      } object;\
      struct {\
         const Type  *arrayType;\
         int32_t      nItems;\
      } array;\
      struct {\
         const Type *seqType;\
         int32_t      nMaxLen;\
      } seqSimple; \
      struct {\
         uint32_t bFloating;\
         uint32_t bSigned;\
      } prim; \
      const SequenceType* seqComplex;\
      const UnionType  *unionType;\
      const StructType *structType;\
      int32_t         stringMaxLen;\
      uint8_t        bInterfaceNotNil;\
   } param;\
   uint8_t    type;\
   uint8_t    nativeAlignment\

typedef struct UnionType UnionType;
typedef struct StructType StructType;
typedef struct SequenceType SequenceType;
struct Type {
   INHERIT_TYPE;
};

struct SequenceType {
   const Type *         seqType;
   uint32_t               nMaxLen;
   uint32_t               inSize;
   uint32_t               routSizePrimIn;
   uint32_t               routSizePrimROut;
};

//byte offset from the start of the case values for
//this unions case value array.  it MUST be aligned
//at the alignment requrements for the descriptor
//
//if negative it means that the unions cases are
//simple enumerators, so the value read from the descriptor
//can be used directly to find the correct case
typedef union CaseValuePtr CaseValuePtr;
union CaseValuePtr {
   const uint8_t*   value8s;
   const uint16_t*  value16s;
   const uint32_t*  value32s;
   const uint64_t*  value64s;
};

//these are only used in complex cases
//so I pulled them out of the type definition as references to make
//the type smaller
struct UnionType {
   const Type           *descriptor;
   uint32_t               nCases;
   const CaseValuePtr   caseValues;
   const Type * const   *cases;
   int32_t               inSize;
   int32_t               routSizePrimIn;
   int32_t               routSizePrimROut;
   uint8_t                inAlignment;
   uint8_t                routAlignmentPrimIn;
   uint8_t                routAlignmentPrimROut;
   uint8_t                inCaseAlignment;
   uint8_t                routCaseAlignmentPrimIn;
   uint8_t                routCaseAlignmentPrimROut;
   uint8_t                nativeCaseAlignment;
   uint8_t              bDefaultCase;
};

struct StructType {
   uint32_t               nMembers;
   const Type * const   *members;
   int32_t               inSize;
   int32_t               routSizePrimIn;
   int32_t               routSizePrimROut;
   uint8_t                inAlignment;
   uint8_t                routAlignmentPrimIn;
   uint8_t                routAlignmentPrimROut;
};

typedef struct Parameter Parameter;
struct Parameter {
   INHERIT_TYPE;
   uint8_t    mode;
   uint8_t  bNotNil;
};

#define SLIM_SCALARS_IS_DYNAMIC(u) (((u) & 0x00ffffff) == 0x00ffffff)

typedef struct Method Method;
struct Method {
   uint32_t                    uScalars;            //no method index
   int32_t                     primInSize;
   int32_t                     primROutSize;
   int                         maxArgs;
   int                         numParams;
   const Parameter * const     *params;
   uint8_t                       primInAlignment;
   uint8_t                       primROutAlignment;
};

typedef struct Interface Interface;

struct Interface {
   int                            nMethods;
   const Method  * const          *methodArray;
   int                            nIIds;
   const uint32_t                   *iids;
   const uint16_t*                  methodStringArray;
   const uint16_t*                  methodStrings;
   const char*                    strings;
};


#endif //SLIM_H


#ifndef _ADSP_FD_SLIM_H
#define _ADSP_FD_SLIM_H
#include "remote.h"
#include <stdint.h>

#ifndef __QAIC_SLIM
#define __QAIC_SLIM(ff) ff
#endif
#ifndef __QAIC_SLIM_EXPORT
#define __QAIC_SLIM_EXPORT
#endif

static const Type types[4];
static const Type* const typeArrays[12] = {&(types[1]),&(types[2]),&(types[2]),&(types[2]),&(types[2]),&(types[1]),&(types[1]),&(types[1]),&(types[1]),&(types[1]),&(types[1]),&(types[3])};
static const StructType structTypes[4] = {{0x7,&(typeArrays[0]),0x2c,0x0,0x2c,0x4,0x1,0x4},{0x1,&(typeArrays[11]),0xc,0x0,0xc,0x4,0x1,0x4},{0x4,&(typeArrays[5]),0x10,0x0,0x10,0x4,0x1,0x4},{0x2,&(typeArrays[5]),0x8,0x0,0x8,0x4,0x1,0x4}};
static const Type types[4] = {{0x1,{{(const uintptr_t)0,(const uintptr_t)0}}, 2,0x1},{0x4,{{(const uintptr_t)0,(const uintptr_t)1}}, 2,0x4},{0x8,{{(const uintptr_t)&(structTypes[3]),0}}, 6,0x4},{0xc,{{(const uintptr_t)&(types[1]),(const uintptr_t)0x3}}, 8,0x4}};
static const Parameter parameters[11] = {{0x1,{{(const uintptr_t)0,(const uintptr_t)0}}, 2,0x1,3,0},{0x4,{{(const uintptr_t)0,(const uintptr_t)1}}, 2,0x4,0,0},{0x8,{{(const uintptr_t)&(types[0]),(const uintptr_t)0x0}}, 9,0x4,0,0},{0x4,{{(const uintptr_t)0,(const uintptr_t)1}}, 2,0x4,3,0},{0x2c,{{(const uintptr_t)&(structTypes[0]),0}}, 6,0x4,3,0},{0xc,{{(const uintptr_t)&(structTypes[1]),0}}, 6,0x4,0,0},{0xc,{{(const uintptr_t)&(structTypes[1]),0}}, 6,0x4,3,0},{0x1,{{(const uintptr_t)0,(const uintptr_t)0}}, 2,0x1,0,0},{0x8,{{(const uintptr_t)&(types[0]),(const uintptr_t)0x0}}, 9,0x4,3,0},{0x10,{{(const uintptr_t)&(structTypes[2]),0}}, 6,0x4,0,0},{0x10,{{(const uintptr_t)&(structTypes[2]),0}}, 6,0x4,3,0}};
static const Parameter* const parameterArrays[51] = {(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[9])),(&(parameters[1])),(&(parameters[9])),(&(parameters[1])),(&(parameters[3])),(&(parameters[3])),(&(parameters[3])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[9])),(&(parameters[1])),(&(parameters[3])),(&(parameters[3])),(&(parameters[3])),(&(parameters[1])),(&(parameters[2])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[10])),(&(parameters[10])),(&(parameters[1])),(&(parameters[9])),(&(parameters[9])),(&(parameters[1])),(&(parameters[1])),(&(parameters[3])),(&(parameters[1])),(&(parameters[6])),(&(parameters[3])),(&(parameters[1])),(&(parameters[5])),(&(parameters[1])),(&(parameters[1])),(&(parameters[1])),(&(parameters[4])),(&(parameters[1])),(&(parameters[0])),(&(parameters[1])),(&(parameters[7])),(&(parameters[0])),(&(parameters[0])),(&(parameters[8]))};
static const Method methods[21] = {{REMOTE_SCALARS_MAKEX(0,0,0x0,0x1,0x0,0x0),0x0,0x2,2,2,(&(parameterArrays[48])),0x1,0x1},{REMOTE_SCALARS_MAKEX(0,0,0x0,0x0,0x0,0x0),0x0,0x0,0,0,0,0x0,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x8,0x0,2,2,(&(parameterArrays[0])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x2,0x0,0x0,0x0),0x18,0x0,7,6,(&(parameterArrays[20])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x4,2,2,(&(parameterArrays[7])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x4,0x0,1,1,(&(parameterArrays[0])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x8,0x2c,3,3,(&(parameterArrays[41])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0xc,0x0,3,3,(&(parameterArrays[0])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x8,3,3,(&(parameterArrays[7])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x14,0x0,3,3,(&(parameterArrays[38])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x10,3,3,(&(parameterArrays[35])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x5,0x0,2,2,(&(parameterArrays[46])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x0,3,1,(&(parameterArrays[50])),0x4,0x1},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x38,0xc,11,11,(&(parameterArrays[0])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x8,0x4,3,3,(&(parameterArrays[32])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x10,0x0,4,4,(&(parameterArrays[0])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0xc,4,4,(&(parameterArrays[7])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x24,0xc,9,9,(&(parameterArrays[11])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x0,0x0,0x0),0x24,0x0,3,3,(&(parameterArrays[29])),0x4,0x0},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x20,3,3,(&(parameterArrays[26])),0x4,0x4},{REMOTE_SCALARS_MAKEX(0,0,0x1,0x1,0x0,0x0),0x4,0x1,2,2,(&(parameterArrays[44])),0x4,0x1}};
static const Method* const methodArrays[41] = {&(methods[0]),&(methods[1]),&(methods[2]),&(methods[3]),&(methods[4]),&(methods[5]),&(methods[5]),&(methods[6]),&(methods[7]),&(methods[8]),&(methods[9]),&(methods[10]),&(methods[11]),&(methods[7]),&(methods[8]),&(methods[2]),&(methods[4]),&(methods[7]),&(methods[8]),&(methods[12]),&(methods[12]),&(methods[1]),&(methods[1]),&(methods[13]),&(methods[7]),&(methods[14]),&(methods[15]),&(methods[2]),&(methods[15]),&(methods[16]),&(methods[17]),&(methods[5]),&(methods[18]),&(methods[19]),&(methods[20]),&(methods[2]),&(methods[4]),&(methods[2]),&(methods[4]),&(methods[7]),&(methods[8])};
static const char strings[1307] = "GetDtRequiredStillMemSize\0GetDtRequiredMovieMemSize\0pnTrackingAngleExtension\0anNonTrackingAngleStruct\0pnNonTrackingThreshold\0pnNonTrackingTimeout\0GetDtModifyMoveRate\0SetDtModifyMoveRate\0pnTrackingThreshold\0panNonTrackingAngle\0GetDtDirectionMask\0prcNonTrackingArea\0GetDtRectangleMask\0SetDtRectangleMask\0GetDtFaceSizeRange\0SetDtFaceSizeRange\0SetDtDirectionMask\0pnTrackingTimeout\0GetDtRefreshCount\0SetDtRefreshCount\0rcNonTrackingEdge\0pnNonTrackingStep\0pnModifyMoveRate\0pnHeadRetryCount\0pnFaceRetryCount\0pnMaxWorkMemSize\0pnMinWorkMemSize\0GetDtMemorySize\0SetDtMemorySize\0prcTrackingArea\0SetDSPPowerPref\0pnBackupMemSize\0FreeBMemoryArea\0FreeWMemoryArea\0DeleteDetection\0CreateDetection\0GetDtLostParam\0SetDtLostParam\0pnRefreshCount\0rcTrackingEdge\0SetBMemoryArea\0SetWMemoryArea\0GetDtThreshold\0SetDtThreshold\0pnTrackingStep\0DeleteDtResult\0GetDtFaceCount\0nMaxSwapNumber\0nMaxFaceNumber\0CreateDtResult\0ClearDtResult\0ptRightBottom\0GetDtFaceInfo\0GetDtTimeout\0SetDtTimeout\0ptLeftBottom\0minorVersion\0majorVersion\0pnHoldCount\0pMemoryAddr\0nConfidence\0GetDtAngle\0SetDtAngle\0ptRightTop\0psFaceInfo\0getVersion\0GetDtMode\0SetDtMode\0pnMaxSize\0pnMinSize\0GetDtStep\0SetDtStep\0ptLeftTop\0hDtResult\0nAccuracy\0DtLockID\0b_absapi\0punSize\0latency\0pnCount\0nHeight\0pbMask\0bottom\0pnMode\0nIndex\0nWidth\0pImage\0clock\0right\0nPose\0left\0bus\0top\0nID\0hDT\0";
static const uint16_t methodStrings[198] = {26,1254,1218,1117,858,413,1286,1295,1274,1233,432,723,1286,1295,1274,1233,435,598,517,500,916,1156,1247,1064,1299,1146,1053,956,902,1280,1019,1252,1174,1252,1174,1252,1174,1252,1174,0,1254,1218,1117,858,413,1286,1295,1274,1233,432,598,517,500,264,1303,245,1286,1295,1274,1233,566,1286,1295,1274,1233,283,1303,246,1286,1295,1274,1233,567,1286,1295,1274,1233,652,1303,1261,1254,1218,1166,1156,678,1303,483,466,995,693,1303,484,467,996,582,1268,1291,1202,1185,1031,1303,206,207,52,1042,1303,77,207,53,930,1303,125,359,943,1303,126,129,377,1303,1241,708,395,1303,1241,709,768,1303,102,186,783,1303,103,106,302,1303,1116,1106,321,1303,1117,1107,1126,1303,431,798,1136,1303,432,435,534,1303,1194,550,1303,1195,146,1303,449,166,1303,450,226,1303,1226,1176,1156,1299,1086,1303,1240,1096,1303,1241,340,1303,1227,828,1156,1210,873,858,843,1075,982,969,888,1156,738,1007,753,1007,646,1303,813,1156,614,630,662};
static const uint16_t methodStringsArrays[41] = {182,197,179,77,176,193,191,20,145,141,104,99,173,137,133,170,167,129,125,189,187,196,195,0,121,117,94,164,89,84,39,185,65,53,161,158,155,152,149,113,109};
__QAIC_SLIM_EXPORT const Interface __QAIC_SLIM(adsp_fd_slim) = {41,&(methodArrays[0]),0,0,&(methodStringsArrays [0]),methodStrings,strings};
#endif //_ADSP_FD_SLIM_H
#ifdef __qdsp6__
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wuninitialized"
#endif
#endif

#ifndef __QAIC_REMOTE
#define __QAIC_REMOTE(ff) ff
#endif //__QAIC_REMOTE

#ifndef __QAIC_HEADER
#define __QAIC_HEADER(ff) ff
#endif //__QAIC_HEADER

#ifndef __QAIC_HEADER_EXPORT
#define __QAIC_HEADER_EXPORT
#endif // __QAIC_HEADER_EXPORT

#ifndef __QAIC_HEADER_ATTRIBUTE
#define __QAIC_HEADER_ATTRIBUTE
#endif // __QAIC_HEADER_ATTRIBUTE

#ifndef __QAIC_IMPL
#define __QAIC_IMPL(ff) ff
#endif //__QAIC_IMPL

#ifndef __QAIC_IMPL_EXPORT
#define __QAIC_IMPL_EXPORT
#endif // __QAIC_IMPL_EXPORT

#ifndef __QAIC_IMPL_ATTRIBUTE
#define __QAIC_IMPL_ATTRIBUTE
#endif // __QAIC_IMPL_ATTRIBUTE

#ifndef __QAIC_STUB
#define __QAIC_STUB(ff) ff
#endif //__QAIC_STUB

#ifndef __QAIC_STUB_EXPORT
#define __QAIC_STUB_EXPORT
#endif // __QAIC_STUB_EXPORT

#ifndef __QAIC_STUB_ATTRIBUTE
#define __QAIC_STUB_ATTRIBUTE
#endif // __QAIC_STUB_ATTRIBUTE

#ifndef __QAIC_SKEL
#define __QAIC_SKEL(ff) ff
#endif //__QAIC_SKEL__

#ifndef __QAIC_SKEL_EXPORT
#define __QAIC_SKEL_EXPORT
#endif // __QAIC_SKEL_EXPORT

#ifndef __QAIC_SKEL_ATTRIBUTE
#define __QAIC_SKEL_ATTRIBUTE
#endif // __QAIC_SKEL_ATTRIBUTE

#ifdef __QAIC_DEBUG__
   #ifndef __QAIC_DBG_PRINTF__
   #define __QAIC_DBG_PRINTF__( ee ) do { printf ee ; } while(0)
   #endif
#else
   #define __QAIC_DBG_PRINTF__( ee ) (void)0
#endif


#define _OFFSET(src, sof)  ((void*)(((char*)(src)) + (sof)))

#define _COPY(dst, dof, src, sof, sz)  \
   do {\
         struct __copy { \
            char ar[sz]; \
         };\
         *(struct __copy*)_OFFSET(dst, dof) = *(struct __copy*)_OFFSET(src, sof);\
   } while (0)

#define _ASSIGN(dst, src, sof)  \
   do {\
      dst = OFFSET(src, sof); \
   } while (0)

#define _STD_STRLEN_IF(str) (str == 0 ? 0 : strlen(str))

#include "AEEStdErr.h"

#define _TRY(ee, func) \
   do { \
      if (AEE_SUCCESS != ((ee) = func)) {\
         __QAIC_DBG_PRINTF__((__FILE_LINE__  ": error: %d\n", (int)(ee)));\
         goto ee##bail;\
      } \
   } while (0)

#define _CATCH(exception) exception##bail: if (exception != AEE_SUCCESS)

#define _ASSERT(nErr, ff) _TRY(nErr, 0 == (ff) ? AEE_EBADPARM : AEE_SUCCESS)

#ifdef __QAIC_DEBUG__
#define _ALLOCATE(nErr, pal, size, alignment, pv) _TRY(nErr, allocator_alloc(pal, __FILE_LINE__, size, alignment, (void**)&pv))
#else
#define _ALLOCATE(nErr, pal, size, alignment, pv) _TRY(nErr, allocator_alloc(pal, 0, size, alignment, (void**)&pv))
#endif


#ifdef __cplusplus
extern "C" {
#endif

#ifndef _const_adsp_fd_handle
#define _const_adsp_fd_handle ((remote_handle)-1)
#endif //_const_adsp_fd_handle

static void _adsp_fd_pls_dtor(void* data) {
   remote_handle* ph = (remote_handle*)data;
   if(_const_adsp_fd_handle != *ph) {
      (void)__QAIC_REMOTE(remote_handle_close)(*ph);
      *ph = _const_adsp_fd_handle;
   }
}

static int _adsp_fd_pls_ctor(void* ctx, void* data) {
   remote_handle* ph = (remote_handle*)data;
   *ph = _const_adsp_fd_handle;
   if(*ph == (remote_handle)-1) {
      return __QAIC_REMOTE(remote_handle_open)((const char*)ctx, ph);
   }
   return 0;
}

#if (defined __qdsp6__) || (defined __hexagon__)
#pragma weak  adsp_pls_add_lookup
extern int adsp_pls_add_lookup(uint32_t type, uint32_t key, int size, int (*ctor)(void* ctx, void* data), void* ctx, void (*dtor)(void* ctx), void** ppo);
#pragma weak  HAP_pls_add_lookup
extern int HAP_pls_add_lookup(uint32_t type, uint32_t key, int size, int (*ctor)(void* ctx, void* data), void* ctx, void (*dtor)(void* ctx), void** ppo);

__QAIC_STUB_EXPORT remote_handle _adsp_fd_handle(void) {
   remote_handle* ph;
   if(adsp_pls_add_lookup) {
      if(0 == adsp_pls_add_lookup((uint32_t)_adsp_fd_handle, 0, sizeof(*ph),  _adsp_fd_pls_ctor, "adsp_fd",  _adsp_fd_pls_dtor, (void**)&ph))  {
         return *ph;
      }
      return (remote_handle)-1;
   } else if(HAP_pls_add_lookup) {
      if(0 == HAP_pls_add_lookup((uint32_t)_adsp_fd_handle, 0, sizeof(*ph),  _adsp_fd_pls_ctor, "adsp_fd",  _adsp_fd_pls_dtor, (void**)&ph))  {
         return *ph;
      }
      return (remote_handle)-1;
   }
   return(remote_handle)-1;
}

#else //__qdsp6__ || __hexagon__

uint32_t _adsp_fd_atomic_CompareAndExchange(uint32_t * volatile puDest, uint32_t uExchange, uint32_t uCompare);

#ifdef _WIN32
#include "Windows.h"
uint32_t _adsp_fd_atomic_CompareAndExchange(uint32_t * volatile puDest, uint32_t uExchange, uint32_t uCompare) {
   return (uint32_t)InterlockedCompareExchange((volatile LONG*)puDest, (LONG)uExchange, (LONG)uCompare);
}
#elif __GNUC__
uint32_t _adsp_fd_atomic_CompareAndExchange(uint32_t * volatile puDest, uint32_t uExchange, uint32_t uCompare) {
   return __sync_val_compare_and_swap(puDest, uCompare, uExchange);
}
#endif //_WIN32


__QAIC_STUB_EXPORT remote_handle _adsp_fd_handle(void) {
   static remote_handle handle = _const_adsp_fd_handle;
   if((remote_handle)-1 != handle) {
      return handle;
   } else {
      remote_handle tmp;
      int nErr = _adsp_fd_pls_ctor("adsp_fd", (void*)&tmp);
      if(nErr) {
         return (remote_handle)-1;
      }
      if(((remote_handle)-1 != handle) || ((remote_handle)-1 != (remote_handle)_adsp_fd_atomic_CompareAndExchange((uint32_t*)&handle, (uint32_t)tmp, (uint32_t)-1))) {
         _adsp_fd_pls_dtor(&tmp);
      }
      return handle;
   }
}

#endif //__qdsp6__

__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_skel_invoke)(uint32_t _sc, remote_arg* _pra) __QAIC_STUB_ATTRIBUTE {
   return __QAIC_REMOTE(remote_handle_invoke)(_adsp_fd_handle(), _sc, _pra);
}

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif
static __inline int _stub_method(remote_handle _handle, uint32_t _mid, uint8_t _rout0[1], uint8_t _rout1[1]) {
   int _numIn[1];
   remote_arg _pra[1];
   uint8_t _primROut[2];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[(_numIn[0] + 0)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 0)].buf.nLen = sizeof(_primROut);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 0, 1, 0, 0), _pra));
   _COPY(_rout0, 0, _primROut, 0, 1);
   _COPY(_rout1, 0, _primROut, 1, 1);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_getVersion)(uint8* majorVersion, uint8* minorVersion) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 0;
   return _stub_method(_adsp_fd_handle(), _mid, (uint8_t*)majorVersion, (uint8_t*)minorVersion);
}
static __inline int _stub_method_1(remote_handle _handle, uint32_t _mid) {
   remote_arg* _pra = 0;
   int _nErr = 0;
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 0, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_CreateDetection)(void) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 1;
   return _stub_method_1(_adsp_fd_handle(), _mid);
}
static __inline int _stub_method_2(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[2];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_CreateDtResult)(int nMaxFaceNumber, int nMaxSwapNumber) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 2;
   return _stub_method_2(_adsp_fd_handle(), _mid, (uint32_t*)&nMaxFaceNumber, (uint32_t*)&nMaxSwapNumber);
}
static __inline int _stub_method_3(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], char* _in1[1], uint32_t _in1Len[1], uint32_t _in2[1], uint32_t _in3[1], uint32_t _in4[1], uint32_t _in5[1]) {
   remote_arg _pra[2];
   uint32_t _primIn[6];
   remote_arg* _praIn;
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1Len, 0, 4);
   _praIn = (_pra + 1);
   _praIn[0].buf.pv = _in1[0];
   _praIn[0].buf.nLen = (1 * _in1Len[0]);
   _COPY(_primIn, 8, _in2, 0, 4);
   _COPY(_primIn, 12, _in3, 0, 4);
   _COPY(_primIn, 16, _in4, 0, 4);
   _COPY(_primIn, 20, _in5, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 2, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_Detection)(int hDT, const uint8* pImage, int pImageLen, int nWidth, int nHeight, int nAccuracy, int hDtResult) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 3;
   return _stub_method_3(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (char**)&pImage, (uint32_t*)&pImageLen, (uint32_t*)&nWidth, (uint32_t*)&nHeight, (uint32_t*)&nAccuracy, (uint32_t*)&hDtResult);
}
static __inline int _stub_method_4(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _rout1[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[1];
   uint32_t _primROut[1];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout1, 0, _primROut, 0, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtFaceCount)(int hDtResult, int* pnCount) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 4;
   return _stub_method_4(_adsp_fd_handle(), _mid, (uint32_t*)&hDtResult, (uint32_t*)pnCount);
}
static __inline int _stub_method_5(remote_handle _handle, uint32_t _mid, uint32_t _in0[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[1];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_DeleteDtResult)(int hDtResult) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 5;
   return _stub_method_5(_adsp_fd_handle(), _mid, (uint32_t*)&hDtResult);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_DeleteDetection)(int hDT) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 6;
   return _stub_method_5(_adsp_fd_handle(), _mid, (uint32_t*)&hDT);
}
static __inline int _stub_method_6(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _rout2[11]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[2];
   uint32_t _primROut[11];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout2, 0, _primROut, 0, 44);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtFaceInfo)(int hDtResult, int nIndex, FACEINFO1* psFaceInfo) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 7;
   return _stub_method_6(_adsp_fd_handle(), _mid, (uint32_t*)&hDtResult, (uint32_t*)&nIndex, (uint32_t*)psFaceInfo);
}
static __inline int _stub_method_7(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _in2[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[3];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _COPY(_primIn, 8, _in2, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtStep)(int hDT, int nNonTrackingStep, int nTrackingStep) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 8;
   return _stub_method_7(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nNonTrackingStep, (uint32_t*)&nTrackingStep);
}
static __inline int _stub_method_8(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _rout1[1], uint32_t _rout2[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[1];
   uint32_t _primROut[2];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout1, 0, _primROut, 0, 4);
   _COPY(_rout2, 0, _primROut, 4, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtStep)(int hDT, int* pnNonTrackingStep, int* pnTrackingStep) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 9;
   return _stub_method_8(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)pnNonTrackingStep, (uint32_t*)pnTrackingStep);
}
static __inline int _stub_method_9(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[3], uint32_t _in2[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[5];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 12);
   _COPY(_primIn, 16, _in2, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtAngle)(int hDT, const trackingAngle_t* anNonTrackingAngleStruct, int nTrackingAngleExtension) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 10;
   return _stub_method_9(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)anNonTrackingAngleStruct, (uint32_t*)&nTrackingAngleExtension);
}
static __inline int _stub_method_10(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _rout1[3], uint32_t _rout2[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[1];
   uint32_t _primROut[4];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout1, 0, _primROut, 0, 12);
   _COPY(_rout2, 0, _primROut, 12, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtAngle)(int hDT, trackingAngle_t* panNonTrackingAngle, int* pnTrackingAngleExtension) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 11;
   return _stub_method_10(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)panNonTrackingAngle, (uint32_t*)pnTrackingAngleExtension);
}
static __inline int _stub_method_11(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint8_t _in1[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[2];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 1);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtDirectionMask)(int hDT, uint8 bMask) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 12;
   return _stub_method_11(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint8_t*)&bMask);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtFaceSizeRange)(int hDT, int nMinSize, int nMaxSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 13;
   return _stub_method_7(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nMinSize, (uint32_t*)&nMaxSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtFaceSizeRange)(int hDT, int* pnMinSize, int* pnMaxSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 14;
   return _stub_method_8(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)pnMinSize, (uint32_t*)pnMaxSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtMode)(int hDT, int nMode) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 15;
   return _stub_method_2(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nMode);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtMode)(int hDT, int* pnMode) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 16;
   return _stub_method_4(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)pnMode);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtThreshold)(int hDT, int nNonTrackingThreshold, int nTrackingThreshold) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 17;
   return _stub_method_7(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nNonTrackingThreshold, (uint32_t*)&nTrackingThreshold);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtThreshold)(int hDT, int* pnNonTrackingThreshold, int* pnTrackingThreshold) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 18;
   return _stub_method_8(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)pnNonTrackingThreshold, (uint32_t*)pnTrackingThreshold);
}
static __inline int _stub_method_12(remote_handle _handle, uint32_t _mid, char* _rout0[1], uint32_t _rout0Len[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[1];
   remote_arg* _praIn;
   remote_arg* _praROut;
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _rout0Len, 0, 4);
   _praIn = (_pra + 1);
   _praROut = (_praIn + _numIn[0] + 0);
   _praROut[0].buf.pv = _rout0[0];
   _praROut[0].buf.nLen = (1 * _rout0Len[0]);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetWMemoryArea)(uint8* pMemoryAddr, int pMemoryAddrLen) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 19;
   return _stub_method_12(_adsp_fd_handle(), _mid, (char**)&pMemoryAddr, (uint32_t*)&pMemoryAddrLen);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetBMemoryArea)(uint8* pMemoryAddr, int pMemoryAddrLen) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 20;
   return _stub_method_12(_adsp_fd_handle(), _mid, (char**)&pMemoryAddr, (uint32_t*)&pMemoryAddrLen);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_FreeWMemoryArea)(void) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 21;
   return _stub_method_1(_adsp_fd_handle(), _mid);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_FreeBMemoryArea)(void) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 22;
   return _stub_method_1(_adsp_fd_handle(), _mid);
}
static __inline int _stub_method_13(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _in2[1], uint32_t _in3[1], uint32_t _in4[4], uint32_t _in5[1], uint32_t _in6[4], uint32_t _in7[1], uint32_t _rout8[1], uint32_t _rout9[1], uint32_t _rout10[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[14];
   uint32_t _primROut[3];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _COPY(_primIn, 8, _in2, 0, 4);
   _COPY(_primIn, 12, _in3, 0, 4);
   _COPY(_primIn, 16, _in4, 0, 16);
   _COPY(_primIn, 32, _in5, 0, 4);
   _COPY(_primIn, 36, _in6, 0, 16);
   _COPY(_primIn, 52, _in7, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout8, 0, _primROut, 0, 4);
   _COPY(_rout9, 0, _primROut, 4, 4);
   _COPY(_rout10, 0, _primROut, 8, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtRequiredMovieMemSize)(int nWidth, int nHeight, int nMinSize, int nMaxFaceNumber, const RECT1* rcNonTrackingEdge, int nNonTrackingStep, const RECT1* rcTrackingEdge, int nTrackingStep, int* pnBackupMemSize, int* pnMinWorkMemSize, int* pnMaxWorkMemSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 23;
   return _stub_method_13(_adsp_fd_handle(), _mid, (uint32_t*)&nWidth, (uint32_t*)&nHeight, (uint32_t*)&nMinSize, (uint32_t*)&nMaxFaceNumber, (uint32_t*)rcNonTrackingEdge, (uint32_t*)&nNonTrackingStep, (uint32_t*)rcTrackingEdge, (uint32_t*)&nTrackingStep, (uint32_t*)pnBackupMemSize, (uint32_t*)pnMinWorkMemSize, (uint32_t*)pnMaxWorkMemSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtRefreshCount)(int hDT, int nMode, int nRefreshCount) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 24;
   return _stub_method_7(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nMode, (uint32_t*)&nRefreshCount);
}
static __inline int _stub_method_14(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _rout2[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[2];
   uint32_t _primROut[1];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout2, 0, _primROut, 0, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtRefreshCount)(int hDT, int nMode, int* pnRefreshCount) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 25;
   return _stub_method_14(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nMode, (uint32_t*)pnRefreshCount);
}
static __inline int _stub_method_15(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _in2[1], uint32_t _in3[1]) {
   remote_arg _pra[1];
   uint32_t _primIn[4];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _COPY(_primIn, 8, _in2, 0, 4);
   _COPY(_primIn, 12, _in3, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDSPPowerPref)(int clock, int bus, int latency, int b_absapi) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 26;
   return _stub_method_15(_adsp_fd_handle(), _mid, (uint32_t*)&clock, (uint32_t*)&bus, (uint32_t*)&latency, (uint32_t*)&b_absapi);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_DtLockID)(int hDtResult, int nID) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 27;
   return _stub_method_2(_adsp_fd_handle(), _mid, (uint32_t*)&hDtResult, (uint32_t*)&nID);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtLostParam)(int hDT, int nFaceRetryCount, int nHeadRetryCount, int nHoldCount) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 28;
   return _stub_method_15(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)&nFaceRetryCount, (uint32_t*)&nHeadRetryCount, (uint32_t*)&nHoldCount);
}
static __inline int _stub_method_16(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _rout1[1], uint32_t _rout2[1], uint32_t _rout3[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[1];
   uint32_t _primROut[3];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout1, 0, _primROut, 0, 4);
   _COPY(_rout2, 0, _primROut, 4, 4);
   _COPY(_rout3, 0, _primROut, 8, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtLostParam)(int hDT, int* pnFaceRetryCount, int* pnHeadRetryCount, int* pnHoldCount) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 29;
   return _stub_method_16(_adsp_fd_handle(), _mid, (uint32_t*)&hDT, (uint32_t*)pnFaceRetryCount, (uint32_t*)pnHeadRetryCount, (uint32_t*)pnHoldCount);
}
static __inline int _stub_method_17(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _in2[1], uint32_t _in3[1], uint32_t _in4[4], uint32_t _in5[1], uint32_t _rout6[1], uint32_t _rout7[1], uint32_t _rout8[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[9];
   uint32_t _primROut[3];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _COPY(_primIn, 8, _in2, 0, 4);
   _COPY(_primIn, 12, _in3, 0, 4);
   _COPY(_primIn, 16, _in4, 0, 16);
   _COPY(_primIn, 32, _in5, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout6, 0, _primROut, 0, 4);
   _COPY(_rout7, 0, _primROut, 4, 4);
   _COPY(_rout8, 0, _primROut, 8, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtRequiredStillMemSize)(int nWidth, int nHeight, int nMinSize, int nMaxFaceNumber, const RECT1* rcNonTrackingEdge, int nNonTrackingStep, int* pnBackupMemSize, int* pnMinWorkMemSize, int* pnMaxWorkMemSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 30;
   return _stub_method_17(_adsp_fd_handle(), _mid, (uint32_t*)&nWidth, (uint32_t*)&nHeight, (uint32_t*)&nMinSize, (uint32_t*)&nMaxFaceNumber, (uint32_t*)rcNonTrackingEdge, (uint32_t*)&nNonTrackingStep, (uint32_t*)pnBackupMemSize, (uint32_t*)pnMinWorkMemSize, (uint32_t*)pnMaxWorkMemSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_ClearDtResult)(int hDtResult) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 31;
   return _stub_method_2(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDtResult);
}
static __inline int _stub_method_18(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _in2[4], uint32_t _in3[4]) {
   remote_arg _pra[1];
   uint32_t _primIn[10];
   int _nErr = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _COPY(_primIn, 8, _in2, 0, 16);
   _COPY(_primIn, 24, _in3, 0, 16);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 0, 0, 0), _pra));
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtRectangleMask)(int hDT, const RECT1* rcNonTrackingArea, const RECT1* rcTrackingArea) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 32;
   return _stub_method_18(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)rcNonTrackingArea, (uint32_t*)rcTrackingArea);
}
static __inline int _stub_method_19(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _rout2[4], uint32_t _rout3[4]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[2];
   uint32_t _primROut[8];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout2, 0, _primROut, 0, 16);
   _COPY(_rout3, 0, _primROut, 16, 16);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtRectangleMask)(int hDT, RECT1* prcNonTrackingArea, RECT1* prcTrackingArea) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 33;
   return _stub_method_19(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)prcNonTrackingArea, (uint32_t*)prcTrackingArea);
}
static __inline int _stub_method_20(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint8_t _rout2[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[2];
   uint8_t _primROut[1];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout2, 0, _primROut, 0, 1);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtDirectionMask)(int hDT, uint8* pbMask) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 34;
   return _stub_method_20(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint8_t*)pbMask);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtModifyMoveRate)(int hDT, int nModifyMoveRate) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 35;
   return _stub_method_7(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)&nModifyMoveRate);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtModifyMoveRate)(int hDT, int* pnModifyMoveRate) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 36;
   return _stub_method_14(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)pnModifyMoveRate);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtMemorySize)(int hDT, int unSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 37;
   return _stub_method_7(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)&unSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtMemorySize)(int hDT, int* punSize) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 38;
   return _stub_method_14(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)punSize);
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_SetDtTimeout)(int hDT, int nNonTrackingTimeout, int nTrackingTimeout) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 39;
   return _stub_method_15(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)&nNonTrackingTimeout, (uint32_t*)&nTrackingTimeout);
}
static __inline int _stub_method_21(remote_handle _handle, uint32_t _mid, uint32_t _in0[1], uint32_t _in1[1], uint32_t _rout2[1], uint32_t _rout3[1]) {
   int _numIn[1];
   remote_arg _pra[2];
   uint32_t _primIn[2];
   uint32_t _primROut[2];
   int _nErr = 0;
   _numIn[0] = 0;
   _pra[0].buf.pv = (void*)_primIn;
   _pra[0].buf.nLen = sizeof(_primIn);
   _pra[(_numIn[0] + 1)].buf.pv = (void*)_primROut;
   _pra[(_numIn[0] + 1)].buf.nLen = sizeof(_primROut);
   _COPY(_primIn, 0, _in0, 0, 4);
   _COPY(_primIn, 4, _in1, 0, 4);
   _TRY(_nErr, __QAIC_REMOTE(remote_handle_invoke)(_handle, REMOTE_SCALARS_MAKEX(0, _mid, 1, 1, 0, 0), _pra));
   _COPY(_rout2, 0, _primROut, 0, 4);
   _COPY(_rout3, 0, _primROut, 4, 4);
   _CATCH(_nErr) {}
   return _nErr;
}
__QAIC_STUB_EXPORT int __QAIC_STUB(adsp_fd_GetDtTimeout)(int hDT, int* pnNonTrackingTimeout, int* pnTrackingTimeout) __QAIC_STUB_ATTRIBUTE {
   uint32_t _mid = 40;
   return _stub_method_21(_adsp_fd_handle(), 31, &_mid, (uint32_t*)&hDT, (uint32_t*)pnNonTrackingTimeout, (uint32_t*)pnTrackingTimeout);
}
#ifdef __cplusplus
}
#endif
#endif //_ADSP_FD_STUB_H
