/**
 * ad5823_actuator.h
 *
 * DESCRIPTION
 *  Auto-Generated by Actuator tool.
 *
 * Copyright (c) 2014-2015 Qualcomm Technologies, Inc. All Rights Reserved.
 *   Qualcomm Technologies Proprietary and Confidential.
 */
  {
    .actuator_params =
    {
      .module_name = "liteon",
      .actuator_name = "ad5823",
      .i2c_addr = 0x18,
      .i2c_freq_mode = SENSOR_I2C_MODE_FAST,
      .i2c_data_type = CAMERA_I2C_WORD_DATA,
      .i2c_addr_type = CAMERA_I2C_BYTE_ADDR,
      .act_type = ACTUATOR_TYPE_VCM,
      .data_size = 10,
      .reg_tbl =
      {
        .reg_tbl_size = 1,
        .reg_params =
        {
          {
            .reg_write_type = ACTUATOR_WRITE_DAC,
            .hw_mask = 0x00000400,
            .reg_addr = 0x04,
            .hw_shift = 0,
            .data_shift = 0,
          },
        },
      },
      .init_setting_size = 5,
      .init_settings =
      {
        {
          .reg_addr = 0x01,
          .addr_type = CAMERA_I2C_BYTE_ADDR,
          .reg_data = 0x00,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .i2c_operation = ACTUATOR_I2C_OP_WRITE,
          .delay = 0,
        },
        {
          .reg_addr = 0x02,
          .addr_type = CAMERA_I2C_BYTE_ADDR,
          .reg_data = 0x13,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .i2c_operation = ACTUATOR_I2C_OP_WRITE,
          .delay = 0,
        },
        {
          .reg_addr = 0x03,
          .addr_type = CAMERA_I2C_BYTE_ADDR,
          .reg_data = 0x80,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .i2c_operation = ACTUATOR_I2C_OP_WRITE,
          .delay = 0,
        },
        {
          .reg_addr = 0x06,
          .addr_type = CAMERA_I2C_BYTE_ADDR,
          .reg_data = 0x00,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .i2c_operation = ACTUATOR_I2C_OP_WRITE,
          .delay = 0,
        },
        {
          .reg_addr = 0x07,
          .addr_type = CAMERA_I2C_BYTE_ADDR,
          .reg_data = 0xA0,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .i2c_operation = ACTUATOR_I2C_OP_WRITE,
          .delay = 0,
        },
      },
    }, /* actuator_params */

    .actuator_tuned_params =
    {
      .scenario_size =
      {
        1, /* MOVE_NEAR */
        1, /* MOVE_FAR */
      },
      .ringing_scenario =
      {
        /* MOVE_NEAR */
        {
          424,
        },
        /* MOVE_FAR */
        {
          424,
        },
      },
      .initial_code = 140,
      .region_size = 1,
      .region_params =
      {
        {
          .step_bound =
          {
            424, /* Macro step boundary*/
            0, /* Infinity step boundary*/
          },
          .code_per_step = 1,
        },
      },
      .damping =
      {
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x3FF,
                .damping_delay = 8000,
                .hw_params = 0x00000400,
              },
            },
          },
        },
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x3FF,
                .damping_delay = 9000,
                .hw_params = 0x00000400,
              },
            },
          },
        },
      },
    }, /* actuator_tuned_params */
  },
