#ifndef CSR_BT_AV_APP_UI_STRINGS_H__
#define CSR_BT_AV_APP_UI_STRINGS_H__

/******************************************************************************

Copyright (c) 2009-2016 Qualcomm Technologies International, Ltd.
All Rights Reserved. 
Qualcomm Technologies International, Ltd. Confidential and Proprietary.

REVISION:      $Revision: #1 $
******************************************************************************/

#include "csr_synergy.h"
#ifndef CSR_BT_APP_MPAA_ENABLE

#include "csr_bt_ui_strings.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TEXT_MAIN_MENU_STRING                             "AV Main Menu"
#define TEXT_AV_ACTIVATE_MENU_STRING                      "AV_ACTIVATE"
#define TEXT_AV_DEACTIVATE_MENU_STRING                    "AV_DEACTIVATE"
#define TEXT_AV_CONNECT_STRING                            "Connect AV"
#define TEXT_AV_DISPLAY_CURRENT_CON_STRING                "Display current con details"
#define TEXT_AV_ESTABLISH_CON_STRING                      "Establish an AV connection"
#define TEXT_AV_TOGGLE_RF_STRING                          "Toggle RF"
#define TEXT_AV_TOGGLE_CONNECTION_STRING                  "Toggle Connection"
#define TEXT_AV_TOGGLED_CONNECTION_STRING                 "Toggled COnnection"
#define TEXT_AV_UNABLE_TO_TOGGLE_CONNECTION_STRING        "Unable to toggle connection in single connection mode"
#define TEXT_AV_RF_SHIELD_ON_STRING                       "RF Shield on"
#define TEXT_AV_RF_SHIELD_OFF_STRING                      "RF Shield off"
#define TEXT_AV_CONNECTION_MODE_STRING                    "AV connection mode"
#define TEXT_AV_SINGLE_CON_STRING                         "AV single connection"
#define TEXT_AV_SINGLE_CON_SELECTED_STRING                "AV single conn selected"
#define TEXT_AV_MULTIPLE_CON_STRING                       "AV multiple connection string"
#define TEXT_AV_MULTIPLE_CON_SELECTED_STRING              "AV multi conn selected"
#define TEXT_AV_MULTI_CON_IN_SINK_MODE_STRING             "Multi-Connection - AV-Mode changed to source"
#define TEXT_AV_MODE_STRING                               "AV mode"
#define TEXT_AV_MODE_SINK_STRING                          "Sink"
#define TEXT_AV_MODE_SINK_SELECTED_STRING                 "Sink selected"
#define TEXT_AV_MODE_SOURCE_STRING                        "Source"
#define TEXT_AV_MODE_SOURCE_SELECTED_STRING               "Source Selected"
#define TEXT_AV_MODE_SELECT_A_DEVICE_STIRNG               "Select a device"
#define TEXT_AV_CONNECTING_STRING                         "AV connecting..."
#define TEXT_AV_CONFIGURE_AND_OPEN_STREAM_STRING          "Configure and Open Stream"
#define TEXT_AV_DISOCONNECT_STRING                        "Disconnect the AV Connection"
#define TEXT_AV_ABORT_STREAM_STRING                       "Abort the Stream"
#define TEXT_AV_FILTER_MENU_STRING                        "Filter Menu"
#define TEXT_AV_START_OR_RESUME_STREAM_STRING             "Start or Resume Stream"
#define TEXT_AV_RECONFIGURE_STREAM_STRING                 "Reconfigure Stream"
#define TEXT_AV_CLOSE_STREAM_STRING                       "Close Stream"
#define TEXT_AV_GET_STREAM_CONFIGURATION_STRING           "Get Stream Configuration"
#define TEXT_AV_STREAM_SUCCESSFULLY_OPENED_STRING         "Stream Successfully Opened"
#define TEXT_AV_SUSPEND_STREAM_STRING                     "Suspend Stream"
#define TEXT_AV_CSR_WINDOWS_GRABBER_STRING                "CSR Windows Grabber"
#define TEXT_AV_WINDOWS_GRABBER_MENU_NOT_SUPPORTED_STRING "Windows Grabber doesn't support menu options"
#define TEXT_AV_CSR_SBC_ENCODER_STRING                    "CSR SBC Encoder"
#define TEXT_AV_SBC_CAPABILITIES_STRING                   "SBC capabilities"
#define TEXT_AV_CHANGE_FILENAME_STRING                    "Change Filename"
#define TEXT_AV_CHOOSE_STRING                             "Choose one of the following"
#define TEXT_AV_CHANNEL_MODE_STRING                       "Channel mode"
#define TEXT_AV_ALLOCATION_METHOD_STRING                  "Allocation method"
#define TEXT_AV_PCM_SAMPLE_FREQUENCY_STRING               "PCM sample frequency"
#define TEXT_AV_PCM_CHANNELS_STRING                       "PCM channels"
#define TEXT_AV_SBC_BLOCKS_STRING                         "SBC blocks"
#define TEXT_AV_SBC_SUBBANDS_STRING                       "SBC subbands"
#define TEXT_AV_MINIM_BITPOOL_STRING                      "Minimum bitpool"
#define TEXT_AV_MAXM_BITPOOL_STRING                       "Maximum bitpool"
#define TEXT_AV_MAXM_FRME_SIZE_STRING                     "Maximum frame size"
#define TEXT_AV_CSR_SOURCE_TRANSMITTER_STRING             "CSR Source Transmitter"
#define TEXT_AV_FILTER_TERMINATOR_MENU_NOT_SUPPORTED_STRING "AV2 filter terminators does not support menu options"
#define TEXT_AV_CSR_SBC_DECODER_STRING                    "csr_sbc_decoder"
#define TEXT_AV_CSR_WINDOWS_PLAYBACK_STRING               "csr_windows_playback"
#define TEXT_AV_WINDOWS_PLAYBACK_FILTER_MENY_NOT_SUPPORTED_STRING  "Windows playback filter does not support menu"
#define TEXT_AV_CSR_SINK_TERMINATOR_STRING                "csr_sink_terminator"
#define TEXT_AV_CANCEL_FILTER_SELECTION_STRING            "Cancel Filter Selection"
#define TEXT_AV_DISCONNECT_CFM_STRING                     "AV Disconnected"
#define TEXT_AV_STREAM_CLOSED_STRING                      "Stream closed"
#define TEXT_AV_STREAM_ABORTED_STRING                     "Stream aborted"
#define TEXT_AV_SBC_CAPABILITIES_UI_STRING                "Please enter new setting,SBC capabilities (0xFF 0xFF 0x02 0xFA):"
#define TEXT_AV_PCM_CHANNEL_MODE_UI_STRING                "Please enter new setting,Channel mode (3):"
#define TEXT_AV_ALLOCATION_METHOD_UI_STRING               "Please enter new setting,Allocation method (0):"
#define TEXT_AV_PCM_SAMPLE_FREQUENCY_UI_STRING            "Please enter new setting,PCM sample frequency (48000):"
#define TEXT_AV_PCM_CHANNELS_UI_STRING                    "Please enter new setting,PCM channels (2):"
#define TEXT_AV_SBC_BLOCKS_UI_STRING                      "Please enter new setting,SBC blocks (16):"
#define TEXT_AV_SBC_SUBBANDS_UI_STRING                    "Please enter new setting,SBC subbands (8):"
#define TEXT_AV_SBC_MIN_BITPOOL_UI_STRING                 "Please enter new setting,Minimum bitpool (2):"
#define TEXT_AV_SBC_MAX_BITPOOL_UI_STRING                 "Please enter new setting,Maximum bitpool (250):"
#define TEXT_AV_SBC_MAX_FR_SIZE_UI_STRING                 "Please enter new setting,Maximum frame size (668):"
#define TEXT_AV_CANCEL_FILTER_SELECTION_STRING            "Cancel Filter Selection"
#define TEXT_AV_CANCEL_FILTER_CONFIG_STRING               "Cancel Filter Config"
#define TEXT_AV_SBC_FILE_STREAMER_STRING                  "CSR sbcfile streamer"
#define TEXT_AV_SBC_FILE_WRITER_STRING                    "CSR SBCfile writer"
#define TEXT_AV_MP3_STREAMER_STRING                       "CSR mp3 streamer"
#define TEXT_AV_AAC_STREAMER_STRING                       "CSR aac streamer"
#define TEXT_AV_RAW_FILEDUMP_STRING                       "CSR raw filedump"
#define TEXT_AV_CSR_WAVE_STREAMER_STRING                  "CSR wave streamer"
#define TEXT_AV_CSR_WAVE_WRITER_STRING                    "CSR wave writer"
#define TEXT_AV_REGISTER_DEREGISTER_FOR_EVENT_NOTFCN_STRING "Register/Deregister for event notification"
#define TEXT_AV_CHANGE_ROLE_SRING                         "Change role"
#define TEXT_AV_CHOOSE_ENCODER_SRING                      "Choose on-chip encoder"
#define TEXT_AV_CHOOSE_SBC_ENCODER_SRING                  "Choose SBC on-chip encoder"
#define TEXT_AV_CHOOSE_APTX_ENCODER_SRING                 "Choose Apt-X on-chip encoder"
#define TEXT_AV_SBC_ENCODER_SELECTED_SRING                "On-chip SBC encoder selected"
#define TEXT_AV_APTX_ENCODER_SELECTED_SRING               "On-chip Apt-X encoder selected"
#define TEXT_AV_CHOOSE_ENCODER_INPUT_STRING               "Choose on-chip endpoint type"
#define TEXT_AV_CHOOSE_ENCODER_CODEC_INPUT_STRING         "CODEC"
#define TEXT_AV_CHOOSE_ENCODER_PCM_INPUT_STRING           "PCM"
#define TEXT_AV_CODEC_ENDPOINT_SELECTED_STRING            "CODEC selected" 
#define TEXT_AV_PCM_ENDPOINT_SELECTED_STRING              "PCM selected" 
#define TEXT_AV_TOGGLE_MP3_SUPPORT_STRING                 "Toggle MP3 Support"
#define TEXT_AV_TOGGLE_MP3_ENABLED_STRING                 "MP3 Codec Enabled"
#define TEXT_AV_TOGGLE_MP3_DISABLED_STRING                "MP3 Codec Disabled"

/* UI text defines */
#define TEXT_MAIN_MENU_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_MAIN_MENU_STRING)
#define TEXT_AV_ACTIVATE_MENU_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_ACTIVATE_MENU_STRING)
#define TEXT_AV_DEACTIVATE_MENU_UCS2               CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_DEACTIVATE_MENU_STRING)
#define TEXT_AV_CONNECT_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CONNECT_STRING)
#define TEXT_AV_DISPLAY_CURRENT_CON_UCS2           CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_DISPLAY_CURRENT_CON_STRING)
#define TEXT_AV_ESTABLISH_CON_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_ESTABLISH_CON_STRING)
#define TEXT_AV_TOGGLE_RF_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLE_RF_STRING)
#define TEXT_AV_RF_SHIELD_ON_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_RF_SHIELD_ON_STRING)
#define TEXT_AV_RF_SHIELD_OFF_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_RF_SHIELD_OFF_STRING)
#define TEXT_AV_CONNECTION_MODE_UCS2               CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CONNECTION_MODE_STRING)
#define TEXT_AV_SINGLE_CON_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SINGLE_CON_STRING)
#define TEXT_AV_MULTIPLE_CON_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MULTIPLE_CON_STRING)
#define TEXT_AV_MODE_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_STRING)
#define TEXT_AV_MODE_SINK_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_SINK_STRING)
#define TEXT_AV_MODE_SOURCE_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_SOURCE_STRING)
#define TEXT_AV_MODE_SELECT_A_DEVICE_UCS2          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_SELECT_A_DEVICE_STIRNG)
#define TEXT_AV_CONNECTING_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CONNECTING_STRING)
#define TEXT_AV_CONFIGURE_AND_OPEN_STREAM_UCS2     CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CONFIGURE_AND_OPEN_STREAM_STRING)
#define TEXT_AV_DISOCONNECT_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_DISOCONNECT_STRING)
#define TEXT_AV_ABORT_STREAM_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_ABORT_STREAM_STRING)
#define TEXT_AV_FILTER_MENU_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_FILTER_MENU_STRING)
#define TEXT_AV_START_OR_RESUME_STREAM_UCS2        CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_START_OR_RESUME_STREAM_STRING)
#define TEXT_AV_RECONFIGURE_STREAM_UCS2            CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_RECONFIGURE_STREAM_STRING)
#define TEXT_AV_CLOSE_STREAM_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CLOSE_STREAM_STRING)
#define TEXT_AV_GET_STREAM_CONFIGURATION_UCS2      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_GET_STREAM_CONFIGURATION_STRING)
#define TEXT_AV_STREAM_SUCCESSFULLY_OPENED_UCS2    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_STREAM_SUCCESSFULLY_OPENED_STRING)
#define TEXT_AV_SUSPEND_STREAM_UCS2                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SUSPEND_STREAM_STRING)
#define TEXT_AV_TOGGLE_MP3_SUPPORT_UCS2            CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLE_MP3_SUPPORT_STRING)
#define TEXT_AV_TOGGLE_MP3_ENABLED_UCS2            CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLE_MP3_ENABLED_STRING)
#define TEXT_AV_TOGGLE_MP3_DISABLED_UCS2           CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLE_MP3_DISABLED_STRING)

#define TEXT_AV_CSR_WINDOWS_GRABBER_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_WINDOWS_GRABBER_STRING)
#define TEXT_AV_WINDOWS_GRABBER_MENU_NOT_SUPPORTED_UCS2    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_WINDOWS_GRABBER_MENU_NOT_SUPPORTED_STRING)
#define TEXT_AV_CSR_SBC_ENCODER_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_SBC_ENCODER_STRING)
#define TEXT_AV_SBC_CAPABILITIES_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_CAPABILITIES_STRING)
#define TEXT_AV_CHANNEL_MODE_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHANNEL_MODE_STRING)
#define TEXT_AV_ALLOCATION_METHOD_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_ALLOCATION_METHOD_STRING)
#define TEXT_AV_PCM_SAMPLE_FREQUENCY_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_SAMPLE_FREQUENCY_STRING)
#define TEXT_AV_PCM_CHANNELS_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_CHANNELS_STRING)
#define TEXT_AV_SBC_BLOCKS_UCS2                            CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_BLOCKS_STRING)
#define TEXT_AV_SBC_SUBBANDS_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_SUBBANDS_STRING)
#define TEXT_AV_MINIM_BITPOOL_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MINIM_BITPOOL_STRING)
#define TEXT_AV_MAXM_BITPOOL_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MAXM_BITPOOL_STRING)
#define TEXT_AV_MAXM_FRME_SIZE_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MAXM_FRME_SIZE_STRING)
#define TEXT_AV_CSR_SOURCE_TRANSMITTER_UCS2                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_SOURCE_TRANSMITTER_STRING)
#define TEXT_AV_FILTER_TERMINATOR_MENU_NOT_SUPPORTED_UCS2  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_FILTER_TERMINATOR_MENU_NOT_SUPPORTED_STRING)
#define TEXT_AV_CSR_SBC_DECODER_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_SBC_DECODER_STRING)
#define TEXT_AV_CSR_WINDOWS_PLAYBACK_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_WINDOWS_PLAYBACK_STRING)
#define TEXT_AV_WINDOWS_PLAYBACK_FILTER_MENY_NOT_SUPPORTED_UCS2 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_WINDOWS_PLAYBACK_FILTER_MENY_NOT_SUPPORTED_STRING)
#define TEXT_AV_CSR_SINK_TERMINATOR_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_SINK_TERMINATOR_STRING )
#define TEXT_AV_CANCEL_FILTER_SELECTION_UCS2               CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CANCEL_FILTER_SELECTION_STRING)
#define TEXT_AV_DISCONNECT_CFM_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_DISCONNECT_CFM_STRING)


#define TEXT_AV_STREAM_CLOSED_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_STREAM_CLOSED_STRING)
#define TEXT_AV_STREAM_ABORTED_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_STREAM_ABORTED_STRING)

#define TEXT_AV_SBC_CAPABILITIES_UI_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_CAPABILITIES_UI_STRING)
#define TEXT_AV_PCM_CHANNEL_MODE_UI_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_CHANNEL_MODE_UI_STRING)
#define TEXT_AV_ALLOCATION_METHOD_UI_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_ALLOCATION_METHOD_UI_STRING)
#define TEXT_AV_PCM_SAMPLE_FREQUENCY_UI_UCS2              CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_SAMPLE_FREQUENCY_UI_STRING)
#define TEXT_AV_PCM_CHANNELS_UI_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_CHANNELS_UI_STRING)
#define TEXT_AV_SBC_BLOCKS_UI_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_BLOCKS_UI_STRING)
#define TEXT_AV_SBC_SUBBANDS_UI_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_SUBBANDS_UI_STRING)
#define TEXT_AV_SBC_MIN_BITPOOL_UI_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_MIN_BITPOOL_UI_STRING)
#define TEXT_AV_SBC_MAX_BITPOOL_UI_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_MAX_BITPOOL_UI_STRING)
#define TEXT_AV_SBC_MAX_FR_SIZE_UI_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_MAX_FR_SIZE_UI_STRING)
#define TEXT_AV_CHOOSE_UCS                                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_STRING)
#define TEXT_AV_TOGGLE_CONNECTION_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLE_CONNECTION_STRING)
#define TEXT_AV_TOGGLED_CONNECTION_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_TOGGLED_CONNECTION_STRING)
#define TEXT_AV_UNABLE_TO_TOGGLE_CONNECTION_UCS2          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_UNABLE_TO_TOGGLE_CONNECTION_STRING)
#define TEXT_AV_MODE_SINK_SELECTED_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_SINK_SELECTED_STRING)
#define TEXT_AV_MODE_SOURCE_SELECTED_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MODE_SOURCE_SELECTED_STRING)
#define TEXT_AV_SINGLE_CON_SELECTED_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SINGLE_CON_SELECTED_STRING)
#define TEXT_AV_MULTIPLE_CON_SELECTED_UCS2                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MULTIPLE_CON_SELECTED_STRING)
#define TEXT_AV_MULTI_CON_IN_SINK_MODE_UCS2               CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MULTI_CON_IN_SINK_MODE_STRING)
#define TEXT_AV_CANCEL_FILTER_SELECTION_UCS2              CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CANCEL_FILTER_SELECTION_STRING)
#define TEXT_AV_CANCEL_FILTER_CONFIG_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CANCEL_FILTER_CONFIG_STRING)

#define TEXT_AV_SBC_FILE_STREAMER_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_FILE_STREAMER_STRING)
#define TEXT_AV_SBC_FILE_WRITER_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_FILE_WRITER_STRING)
#define TEXT_AV_CHANGE_FILENAME_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHANGE_FILENAME_STRING)
#define TEXT_AV_MP3_STREAMER_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_MP3_STREAMER_STRING)
#define TEXT_AV_AAC_STREAMER_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_AAC_STREAMER_STRING)
#define TEXT_AV_RAW_FILEDUMP_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_RAW_FILEDUMP_STRING)
#define TEXT_AV_CSR_WAVE_STREAMER_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_WAVE_STREAMER_STRING)
#define TEXT_AV_CSR_WAVE_WRITER_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CSR_WAVE_WRITER_STRING)
#define TEXT_AV_REGISTER_DEREGISTER_FOR_EVENT_NOTFCN_UCS2 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_REGISTER_DEREGISTER_FOR_EVENT_NOTFCN_STRING)
#define TEXT_AV_CHANGE_ROLE_UCS2                          CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHANGE_ROLE_SRING)
#define TEXT_AV_CHOOSE_ENCODER_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_ENCODER_SRING)
#define TEXT_AV_CHOOSE_SBC_ENCODER_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_SBC_ENCODER_SRING)
#define TEXT_AV_CHOOSE_APTX_ENCODER_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_APTX_ENCODER_SRING)
#define TEXT_AV_SBC_ENCODER_SELECTED_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_SBC_ENCODER_SELECTED_SRING)
#define TEXT_AV_APTX_ENCODER_SELECTED_UCS2                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_APTX_ENCODER_SELECTED_SRING)
#define TEXT_AV_CHOOSE_ENCODER_INPUT_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_ENCODER_INPUT_STRING)
#define TEXT_AV_CHOOSE_ENCODER_CODEC_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_ENCODER_CODEC_INPUT_STRING)
#define TEXT_AV_CHOOSE_ENCODER_PCM_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CHOOSE_ENCODER_PCM_INPUT_STRING)
#define TEXT_AV_CODEC_ENDPOINT_SELECTED_UCS2              CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_CODEC_ENDPOINT_SELECTED_STRING)
#define TEXT_AV_PCM_ENDPOINT_SELECTED_UCS2                CONVERT_TEXT_STRING_2_UCS2(TEXT_AV_PCM_ENDPOINT_SELECTED_STRING)




#ifdef __cplusplus
}
#endif

#endif

#endif /* CSR_BT_AV_APP_UI_STRINGS_H__ */
