/**********************************************************************
*  Copyright (c) 2016 Qualcomm Technologies, Inc.
*  All Rights Reserved.
*  Confidential and Proprietary - Qualcomm Technologies, Inc.
**********************************************************************/
#ifndef _ADSP_FD_H
#define _ADSP_FD_H

#include "AEEStdDef.h"
#ifndef __QAIC_HEADER
#define __QAIC_HEADER(ff) ff
#endif //__QAIC_HEADER

#ifndef __QAIC_HEADER_EXPORT
#define __QAIC_HEADER_EXPORT
#endif // __QAIC_HEADER_EXPORT

#ifndef __QAIC_HEADER_ATTRIBUTE
#define __QAIC_HEADER_ATTRIBUTE
#endif // __QAIC_HEADER_ATTRIBUTE

#ifndef __QAIC_IMPL
#define __QAIC_IMPL(ff) ff
#endif //__QAIC_IMPL

#ifndef __QAIC_IMPL_EXPORT
#define __QAIC_IMPL_EXPORT
#endif // __QAIC_IMPL_EXPORT

#ifndef __QAIC_IMPL_ATTRIBUTE
#define __QAIC_IMPL_ATTRIBUTE
#endif // __QAIC_IMPL_ATTRIBUTE
#ifdef __cplusplus
extern "C" {
#endif
typedef unsigned int HCOMMON_SKEL;
typedef unsigned int HDETECTION_SKEL;
typedef unsigned int HDTRESULT_SKEL;
typedef int INT32_SKEL;
typedef unsigned int UINT32_SKEL;
typedef uint8 UINT8_SKEL;
typedef int BOOL_SKEL;
typedef int GRAY_ORDER_SKEL;
typedef int YUV422_ORDER_SKEL;
typedef int YUV420SP_ORDER_SKEL;
typedef int YUV420FP_ORDER_SKEL;
typedef struct POINT_SKEL POINT_SKEL;
struct POINT_SKEL {
   INT32_SKEL x;
   INT32_SKEL y;
};
typedef struct RECT_SKEL RECT_SKEL;
struct RECT_SKEL {
   INT32_SKEL left;
   INT32_SKEL top;
   INT32_SKEL right;
   INT32_SKEL bottom;
};
typedef struct DETECTION_INFO_SKEL DETECTION_INFO_SKEL;
struct DETECTION_INFO_SKEL {
   INT32_SKEL nDetectorType;
   INT32_SKEL nObjectType;
   INT32_SKEL nID;
   INT32_SKEL nConfidence;
   POINT_SKEL ptCenter;
   INT32_SKEL nWidth;
   INT32_SKEL nHeight;
   INT32_SKEL nAngle;
   INT32_SKEL nPose;
   INT32_SKEL nReserved;
   INT32_SKEL nDetectionMethod;
   INT32_SKEL nHoldCount;
   INT32_SKEL nReserved2;
};
typedef struct fpsww_dt_params_t_skel fpsww_dt_params_t_skel;
struct fpsww_dt_params_t_skel {
   UINT8_SKEL majorVersion;
   UINT8_SKEL minorVersion;
   INT32_SKEL nMinSize;
   INT32_SKEL nMaxSize;
   UINT32_SKEL nAngle[3];
   RECT_SKEL faceSearchEdgeMask;
   INT32_SKEL nSearchDensity;
   INT32_SKEL nThreshold;
   INT32_SKEL nInitialFaceSearchCycle;
   INT32_SKEL nNewFaceSearchCycle;
   INT32_SKEL nNewFaceSearchInterval;
   INT32_SKEL nMaxRetryCount;
   INT32_SKEL nMaxHoldCount;
   INT32_SKEL nPosSteadinessParam;
   INT32_SKEL nSizeSteadinessParam;
   INT32_SKEL nTrackingSwapParam;
   INT32_SKEL nDelayCount;
   RECT_SKEL trackingEdgeMask;
   INT32_SKEL nAccuracy;
   BOOL_SKEL rollAngleExtension;
   BOOL_SKEL yawAngleExtension;
   BOOL_SKEL bUseHeadTracking;
   BOOL_SKEL bMask;
};
/********* skel driver specific functions *********/
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FDDSP_GetVersion)(UINT8_SKEL* pucMajor, UINT8_SKEL* pucMinor) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FDDSP_InitDetection)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FDDSP_DeInitDetection)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FDDSP_SetClockConfig)(INT32_SKEL clock, INT32_SKEL bus, INT32_SKEL latency, INT32_SKEL b_absapi) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FDDSP_GetClockConfig)(INT32_SKEL* p_clock, INT32_SKEL* p_bus, INT32_SKEL* p_latency, INT32_SKEL* p_b_absapi) __QAIC_HEADER_ATTRIBUTE;
/********* CO functions *********/
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_GetVersion)(UINT8_SKEL* pucMajor, UINT8_SKEL* pucMinor) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT HCOMMON_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_CreateHandle)(void) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT HCOMMON_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_CreateHandleMemory)(UINT32_SKEL pBMemoryAddr, UINT32_SKEL unBMemorySize, UINT32_SKEL pWMemoryAddr, UINT32_SKEL unWMemorySize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_DeleteHandle)(HCOMMON_SKEL hCO) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_ConvertSquareToCenter)(const POINT_SKEL* ptLeftTop, const POINT_SKEL* ptRightTop, const POINT_SKEL* ptLeftBottom, const POINT_SKEL* ptRightBottom, POINT_SKEL* pptCenter, INT32_SKEL* pnSize, INT32_SKEL* pnAngle) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_CO_ConvertCenterToSquare)(const POINT_SKEL* ptCenter, INT32_SKEL nSize, INT32_SKEL nAngle, POINT_SKEL* pptLeftTop, POINT_SKEL* pptRightTop, POINT_SKEL* pptLeftBottom, POINT_SKEL* pptRightBottom) __QAIC_HEADER_ATTRIBUTE;
/********* DT functions *********/
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetVersion)(UINT8_SKEL* pucMajor, UINT8_SKEL* pucMinor) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT HDETECTION_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_CreateHandle)(HCOMMON_SKEL hCO, INT32_SKEL nDetectionMode, INT32_SKEL nMaxDetectionCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_DeleteHandle)(HDETECTION_SKEL hDT) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT HDTRESULT_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_CreateResultHandle)(HCOMMON_SKEL hCO) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_DeleteResultHandle)(HDTRESULT_SKEL hDtResult) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_Detect_GRAY)(HDETECTION_SKEL hDT, const UINT8_SKEL* pImageGRAY, int pImageGRAYLen, INT32_SKEL nWidth, INT32_SKEL nHeight, GRAY_ORDER_SKEL ImageOrder, HDTRESULT_SKEL hDtResult, INT32_SKEL* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_Detect_YUV422)(HDETECTION_SKEL hDT, const UINT8_SKEL* pImageYUV, int pImageYUVLen, INT32_SKEL nWidth, INT32_SKEL nHeight, YUV422_ORDER_SKEL ImageOrder, HDTRESULT_SKEL hDtResult, INT32_SKEL* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_Detect_YUV420SP)(HDETECTION_SKEL hDT, const UINT8_SKEL* pImageY, int pImageYLen, const UINT8_SKEL* pImageCx, int pImageCxLen, INT32_SKEL nWidth, INT32_SKEL nHeight, YUV420SP_ORDER_SKEL ImageOrder, HDTRESULT_SKEL hDtResult, INT32_SKEL* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_Detect_YUV420FP)(HDETECTION_SKEL hDT, const UINT8_SKEL* pImageY, int pImageYLen, const UINT8_SKEL* pImageCb, int pImageCbLen, const UINT8_SKEL* pImageCr, int pImageCrLen, INT32_SKEL nWidth, INT32_SKEL nHeight, YUV420FP_ORDER_SKEL ImageOrder, HDTRESULT_SKEL hDtResult, INT32_SKEL* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetResultCount)(HDTRESULT_SKEL hDtResult, INT32_SKEL* pnCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetResultInfo)(HDTRESULT_SKEL hDtResult, INT32_SKEL nIndex, DETECTION_INFO_SKEL* psDetectionInfo) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetRawResultInfo)(HDTRESULT_SKEL hDtResult, INT32_SKEL nIndex, DETECTION_INFO_SKEL* psDetectionInfo) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetAllResultInfo)(HDTRESULT_SKEL hDtResult, DETECTION_INFO_SKEL* psDetectionInfo, int psDetectionInfoLen) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetAllRawResultInfo)(HDTRESULT_SKEL hDtResult, DETECTION_INFO_SKEL* psDetectionInfo, int psDetectionInfoLen) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetSizeRange)(HDETECTION_SKEL hDT, INT32_SKEL nMinSize, INT32_SKEL nMaxSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetSizeRange)(HDETECTION_SKEL hDT, INT32_SKEL* pnMinSize, INT32_SKEL* pnMaxSize) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetAngle)(HDETECTION_SKEL hDT, UINT32_SKEL nPose, UINT32_SKEL nAngle) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetAngle)(HDETECTION_SKEL hDT, UINT32_SKEL nPose, UINT32_SKEL* pnAngle) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetEdgeMask)(HDETECTION_SKEL hDT, const RECT_SKEL* rcEdgeMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetEdgeMask)(HDETECTION_SKEL hDT, RECT_SKEL* prcEdgeMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetSearchDensity)(HDETECTION_SKEL hDT, INT32_SKEL nSearchDensity) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetSearchDensity)(HDETECTION_SKEL hDT, INT32_SKEL* pnSearchDensity) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetThreshold)(HDETECTION_SKEL hDT, INT32_SKEL nThreshold) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetThreshold)(HDETECTION_SKEL hDT, INT32_SKEL* pnThreshold) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_ResetTracking)(HDETECTION_SKEL hDT) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_ToggleTrackingLock)(HDETECTION_SKEL hDT, INT32_SKEL nID) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetSearchCycle)(HDETECTION_SKEL hDT, INT32_SKEL nInitialFaceSearchCycle, INT32_SKEL nNewFaceSearchCycle, INT32_SKEL nNewFaceSearchInterval) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetSearchCycle)(HDETECTION_SKEL hDT, INT32_SKEL* pnInitialFaceSearchCycle, INT32_SKEL* pnNewFaceSearchCycle, INT32_SKEL* pnNewFaceSearchInterval) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetLostParam)(HDETECTION_SKEL hDT, INT32_SKEL nMaxRetryCount, INT32_SKEL nMaxHoldCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetLostParam)(HDETECTION_SKEL hDT, INT32_SKEL* pnMaxRetryCount, INT32_SKEL* pnMaxHoldCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetSteadinessParam)(HDETECTION_SKEL hDT, INT32_SKEL nPosSteadinessParam, INT32_SKEL nSizeSteadinessParam) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetSteadinessParam)(HDETECTION_SKEL hDT, INT32_SKEL* pnPosSteadinessParam, INT32_SKEL* pnSizeSteadinessParam) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetTrackingSwapParam)(HDETECTION_SKEL hDT, INT32_SKEL nTrackingSwapParam) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetTrackingSwapParam)(HDETECTION_SKEL hDT, INT32_SKEL* pnTrackingSwapParam) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetDelayCount)(HDETECTION_SKEL hDT, INT32_SKEL nDelayCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetDelayCount)(HDETECTION_SKEL hDT, INT32_SKEL* pnDelayCount) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetTrackingEdgeMask)(HDETECTION_SKEL hDT, const RECT_SKEL* rcEdgeMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetTrackingEdgeMask)(HDETECTION_SKEL hDT, RECT_SKEL* prcEdgeMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetAccuracy)(HDETECTION_SKEL hDT, INT32_SKEL nAccuracy) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetAccuracy)(HDETECTION_SKEL hDT, INT32_SKEL* pnAccuracy) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetAngleExtension)(HDETECTION_SKEL hDT, BOOL_SKEL bExtension) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetAngleExtension)(HDETECTION_SKEL hDT, BOOL_SKEL* pbExtension) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetPoseExtension)(HDETECTION_SKEL hDT, BOOL_SKEL bExtension, BOOL_SKEL bUseHeadTracking) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetPoseExtension)(HDETECTION_SKEL hDT, BOOL_SKEL* pbExtension, BOOL_SKEL* pbUseHeadTracking) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_SetDirectionMask)(HDETECTION_SKEL hDT, BOOL_SKEL bMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_MV_GetDirectionMask)(HDETECTION_SKEL hDT, BOOL_SKEL* pbMask) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_SetDTConfig)(HDETECTION_SKEL hDT, INT32_SKEL detection_mode, const fpsww_dt_params_t_skel* p_dt_params) __QAIC_HEADER_ATTRIBUTE;
__QAIC_HEADER_EXPORT INT32_SKEL __QAIC_HEADER(adsp_fd_FACEPROC_DT_GetDTConfig)(HDETECTION_SKEL hDT, INT32_SKEL detection_mode, fpsww_dt_params_t_skel* p_dt_new_params) __QAIC_HEADER_ATTRIBUTE;
#ifdef __cplusplus
}
#endif
#endif //_ADSP_FD_H
