/* ov9281_lib.h
 *
 * DESCRIPTION: ov9281 sensor library
 * Auto-Generated by Sensor Driver Generator tool
 *
 * Copyright (c) 2017 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

#ifndef __OV9281L_LIB_H__
#define __OV9281L_LIB_H__

#include "sensor_lib.h"
#define SENSOR_MODEL "ov9281"

#define NEW 1

#define START_REG_ARRAY \
{ \
  {0x0100, 0x01, 0}, \
}

#define STOP_REG_ARRAY \
{ \
  {0x0100, 0x00, 66000}, \
}

#define GROUPON_REG_ARRAY \
{ \
  {0x3208, 0x00, 0x00}, \
}

#define GROUPOFF_REG_ARRAY \
{ \
  {0x3208, 0x10, 0x00}, \
  {0x3208, 0xa0, 0x00}, \
}

#define INIT0_REG_ARRAY \
{ \
  {0x0103, 0x01, 0x00}, \
  {0x303B, 0x02, 0x00}, \
}

#define MASTER_SYNC_REG_ARRAY \
{ \
  {0x4315, 0x00, 0x00}, \
  {0x3006, 0x06, 0x00}, \
}

#define SLAVE_SYNC_REG_ARRAY \
{ \
  {0x3666, 0x00, 0x00}, \
  {0x3823, 0x30, 0x00}, \
  {0x3824, 0x01, 0x00}, \
  {0x3825, 0x07, 0x00}, \
  {0x3826, 0x00, 0x00}, \
  {0x3827, 0x00, 0x00}, \
  {0x3006, 0x04, 0x00}, \
}

#define RES0_REG_ARRAY \
{ \
  /* 1280 x 800 */      \
  {0x0103, 0x01, 0x00}, \
  {0x0302, 0x30, 0x00}, \
  {0x030d, 0x50, 0x00}, \
  {0x030e, 0x06, 0x00}, \
  {0x3001, 0x00, 0x00}, \
  {0x3004, 0x00, 0x00}, \
  {0x3005, 0x00, 0x00}, \
  {0x3006, 0x04, 0x00}, \
  {0x3011, 0x0a, 0x00}, \
  {0x3013, 0x18, 0x00}, \
  {0x301c, 0xf0, 0x00}, \
  {0x3022, 0x01, 0x00}, \
  {0x3030, 0x10, 0x00}, \
  {0x3039, 0x32, 0x00}, \
  {0x303a, 0x00, 0x00}, \
  {0x3500, 0x00, 0x00}, \
  {0x3501, 0x2a, 0x00}, \
  {0x3502, 0x90, 0x00}, \
  {0x3503, 0x08, 0x00}, \
  {0x3505, 0x8c, 0x00}, \
  {0x3507, 0x03, 0x00}, \
  {0x3508, 0x00, 0x00}, \
  {0x3509, 0x10, 0x00}, \
  {0x3610, 0x80, 0x00}, \
  {0x3611, 0xa0, 0x00}, \
  {0x3620, 0x6e, 0x00}, \
  {0x3632, 0x56, 0x00}, \
  {0x3633, 0x78, 0x00}, \
  {0x3662, 0x01, 0x00}, \
  {0x3666, 0x00, 0x00}, \
  {0x366f, 0x5a, 0x00}, \
  {0x3680, 0x84, 0x00}, \
  {0x3712, 0x80, 0x00}, \
  {0x372d, 0x22, 0x00}, \
  {0x3731, 0x80, 0x00}, \
  {0x3732, 0x30, 0x00}, \
  {0x3778, 0x00, 0x00}, \
  {0x377d, 0x22, 0x00}, \
  {0x3788, 0x02, 0x00}, \
  {0x3789, 0xa4, 0x00}, \
  {0x378a, 0x00, 0x00}, \
  {0x378b, 0x4a, 0x00}, \
  {0x3799, 0x20, 0x00}, \
  {0x3800, 0x00, 0x00}, \
  {0x3801, 0x00, 0x00}, \
  {0x3802, 0x00, 0x00}, \
  {0x3803, 0x00, 0x00}, \
  {0x3804, 0x05, 0x00}, \
  {0x3805, 0x0f, 0x00}, \
  {0x3806, 0x03, 0x00}, \
  {0x3807, 0x2f, 0x00}, \
  {0x3808, 0x05, 0x00}, \
  {0x3809, 0x00, 0x00}, \
  {0x380a, 0x03, 0x00}, \
  {0x380b, 0x20, 0x00}, \
  {0x380c, 0x02, 0x00}, \
  {0x380d, 0xd8, 0x00}, \
  {0x380e, 0x07, 0x00}, \
  {0x380f, 0x28, 0x00}, \
  {0x3810, 0x00, 0x00}, \
  {0x3811, 0x08, 0x00}, \
  {0x3812, 0x00, 0x00}, \
  {0x3813, 0x08, 0x00}, \
  {0x3814, 0x11, 0x00}, \
  {0x3815, 0x11, 0x00}, \
  {0x3820, 0x40, 0x00}, \
  {0x3821, 0x00, 0x00}, \
  {0x3881, 0x42, 0x00}, \
  {0x38a8, 0x02, 0x00}, \
  {0x38a9, 0x80, 0x00}, \
  {0x38b1, 0x00, 0x00}, \
  {0x38c4, 0x00, 0x00}, \
  {0x38c5, 0xc0, 0x00}, \
  {0x38c6, 0x04, 0x00}, \
  {0x38c7, 0x80, 0x00}, \
  {0x3920, 0xff, 0x00}, \
  {0x4003, 0x40, 0x00}, \
  {0x4008, 0x04, 0x00}, \
  {0x4009, 0x0b, 0x00}, \
  {0x400c, 0x00, 0x00}, \
  {0x400d, 0x07, 0x00}, \
  {0x4010, 0x40, 0x00}, \
  {0x4043, 0x40, 0x00}, \
  {0x4307, 0x30, 0x00}, \
  {0x4317, 0x00, 0x00}, \
  {0x4501, 0x00, 0x00}, \
  {0x4507, 0x00, 0x00}, \
  {0x4509, 0x00, 0x00}, \
  {0x450a, 0x08, 0x00}, \
  {0x4601, 0x04, 0x00}, \
  {0x470f, 0x00, 0x00}, \
  {0x4f07, 0x00, 0x00}, \
  {0x4800, 0x00, 0x00}, \
  {0x4837, 0x15, 0x00}, \
  {0x5000, 0x9f, 0x00}, \
  {0x5001, 0x00, 0x00}, \
  {0x5e00, 0x00, 0x00}, \
  {0x5d00, 0x07, 0x00}, \
  {0x5d01, 0x00, 0x00} \
}

#define RES1_REG_ARRAY \
{ \
  /* 640 x 400 */        \
  {0x0302, 0x32, 0x00}, \
  {0x030d, 0x50, 0x00}, \
  {0x030e, 0x02, 0x00}, \
  {0x3001, 0x00, 0x00}, \
  {0x3004, 0x00, 0x00}, \
  {0x3005, 0x00, 0x00}, \
  {0x3006, 0x04, 0x00}, \
  {0x3011, 0x0a, 0x00}, \
  {0x3013, 0x18, 0x00}, \
  {0x301c, 0xf0, 0x00}, \
  {0x3022, 0x01, 0x00}, \
  {0x3030, 0x10, 0x00}, \
  {0x3039, 0x12, 0x00}, \
  {0x303a, 0x00, 0x00}, \
\
  {0x3500, 0x00, 0x00}, \
  {0x3501, 0x7F, 0x00}, \
  {0x3502, 0x1e, 0x00}, \
\
  {0x3503, 0x08, 0x00}, \
\
  {0x3505, 0x8c, 0x00}, \
  {0x3507, 0x03, 0x00}, \
  {0x3508, 0x00, 0x00}, \
\
  {0x3509, 0x10, 0x00}, \
\
  {0x3610, 0x80, 0x00}, \
  {0x3611, 0xa0, 0x00}, \
  {0x3620, 0x6e, 0x00}, \
  {0x3632, 0x56, 0x00}, \
  {0x3633, 0x78, 0x00}, \
  {0x3662, 0x01, 0x00}, \
  {0x3666, 0x00, 0x00}, \
  {0x366f, 0x5a, 0x00}, \
  {0x3680, 0x84, 0x00}, \
  {0x3712, 0x80, 0x00}, \
  {0x372d, 0x22, 0x00}, \
  {0x3731, 0x80, 0x00}, \
  {0x3732, 0x30, 0x00}, \
  {0x3778, 0x10, 0x00}, \
  {0x377d, 0x22, 0x00}, \
  {0x3788, 0x02, 0x00}, \
  {0x3789, 0xa4, 0x00}, \
  {0x378a, 0x00, 0x00}, \
  {0x378b, 0x4a, 0x00}, \
  {0x3799, 0x20, 0x00}, \
  {0x3800, 0x00, 0x00}, \
  {0x3801, 0x00, 0x00}, \
  {0x3802, 0x00, 0x00}, \
  {0x3803, 0x00, 0x00}, \
  {0x3804, 0x05, 0x00}, \
  {0x3805, 0x0f, 0x00}, \
  {0x3806, 0x03, 0x00}, \
  {0x3807, 0x2f, 0x00}, \
  {0x3808, 0x02, 0x00}, \
  {0x3809, 0x80, 0x00}, \
  {0x380a, 0x01, 0x00}, \
  {0x380b, 0x90, 0x00}, \
  {0x380c, 0x02, 0x00}, \
  {0x380d, 0xd8, 0x00}, \
  {0x380e, 0x0e, 0x00}, \
  {0x380f, 0x50, 0x00}, \
  {0x3810, 0x00, 0x00}, \
  {0x3811, 0x04, 0x00}, \
  {0x3812, 0x00, 0x00}, \
  {0x3813, 0x04, 0x00}, \
  {0x3814, 0x31, 0x00}, \
  {0x3815, 0x22, 0x00}, \
  {0x3820, 0x60, 0x00}, \
  {0x3821, 0x01, 0x00}, \
  {0x3881, 0x42, 0x00}, \
  {0x38a8, 0x02, 0x00}, \
  {0x38a9, 0x80, 0x00}, \
  {0x38b1, 0x00, 0x00}, \
  {0x38c4, 0x00, 0x00}, \
  {0x38c5, 0xc0, 0x00}, \
  {0x38c6, 0x04, 0x00}, \
  {0x38c7, 0x80, 0x00}, \
  {0x3920, 0xff, 0x00}, \
  {0x4003, 0x40, 0x00}, \
  {0x4008, 0x02, 0x00}, \
  {0x4009, 0x05, 0x00}, \
  {0x400c, 0x00, 0x00}, \
  {0x400d, 0x03, 0x00}, \
  {0x4010, 0x40, 0x00}, \
  {0x4043, 0x40, 0x00}, \
  {0x4307, 0x30, 0x00}, \
  {0x4317, 0x00, 0x00}, \
  {0x4501, 0x00, 0x00}, \
  {0x4507, 0x03, 0x00}, \
  {0x4509, 0x80, 0x00}, \
  {0x450a, 0x08, 0x00}, \
  {0x4601, 0x04, 0x00}, \
  {0x470f, 0x00, 0x00}, \
  {0x4f07, 0x00, 0x00}, \
  {0x4800, 0x00, 0x00}, \
  {0x5000, 0x9f, 0x00}, \
  {0x5001, 0x00, 0x00}, \
  {0x5e00, 0x00, 0x00}, \
  {0x5d00, 0x07, 0x00}, \
  {0x5d01, 0x00, 0x00} \
}


static sensor_lib_t sensor_lib_ptr =
{
  .sensor_slave_info =
  {
    .sensor_name = SENSOR_MODEL,
    .slave_addr = 0xC0,
    .i2c_freq_mode = SENSOR_I2C_MODE_FAST,

    .addr_type = CAMERA_I2C_WORD_ADDR,
    .sensor_id_info =
    {
      .sensor_id_reg_addr = 0x300a,
      .sensor_id = 0x9281,
    },
    .power_setting_array =
    {
      .power_setting_a =
      {
        {
          .seq_type = CAMERA_POW_SEQ_VREG,
          .seq_val = CAMERA_VIO,
          .config_val = 0,
          .delay = 0,
        },
        {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_STANDBY,
          .config_val = GPIO_OUT_LOW,
          .delay = 3,
        },
        {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_RESET,
          .config_val = GPIO_OUT_LOW,
          .delay = 3,
        },
        {
          .seq_type = CAMERA_POW_SEQ_VREG,
          .seq_val = CAMERA_VIO,
          .config_val = 1,
          .delay = 0,
        },
        {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_STANDBY,
          .config_val = GPIO_OUT_HIGH,
          .delay = 3,
        },
        {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_RESET,
          .config_val = GPIO_OUT_HIGH,
          .delay = 3,
        },
        {
          .seq_type = CAMERA_POW_SEQ_CLK,
          .seq_val = CAMERA_MCLK,
          .config_val = 24000000,
          .delay = 1,
        },
      },
      .size = 7,
      .power_down_setting_a =
      {
        {
          .seq_type = CAMERA_POW_SEQ_CLK,
          .seq_val = CAMERA_MCLK,
          .config_val = 0,
          .delay = 1,
        },
        {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_RESET,
          .config_val = GPIO_OUT_LOW,
          .delay = 1,
        },
        {
          .seq_type = CAMERA_POW_SEQ_VREG,
          .seq_val = CAMERA_VIO,
          .config_val = 0,
          .delay = 0,
        },
         {
          .seq_type = CAMERA_POW_SEQ_GPIO,
          .seq_val = CAMERA_GPIO_STANDBY,
          .config_val = GPIO_OUT_LOW,
          .delay = 3,
        },

      },
      .size_down = 4,
    },
  },
  .sensor_output =
  {
    .output_format = SENSOR_BAYER,
    .connection_mode = SENSOR_MIPI_CSI,
    .raw_output = SENSOR_10_BIT_DIRECT,
    .filter_arrangement = SENSOR_Y,
  },
  .output_reg_addr =
  {
    .x_output = 0x3808,
    .y_output = 0x380a,
    .line_length_pclk = 0x380c,
    .frame_length_lines = 0x380e,
  },
  .exp_gain_info =
  {
    .coarse_int_time_addr = 0x3501,
    .global_gain_addr = 0x3509,
    .vert_offset = 6,
  },
  .aec_info =
  {
    .min_gain = 1.0,
    .max_gain = 16.0,
    .max_analog_gain = 16.0,
    .max_linecount = 3658,
  },
  .sensor_num_frame_skip = 2,
  .sensor_num_HDR_frame_skip = 0,
  .sensor_max_pipeline_frame_delay = 2,
  .pixel_array_size_info =
  {
    .active_array_size =
    {
      .width = 1280,
      .height = 800,
    },
    .left_dummy = 0,
    .right_dummy = 0,
    .top_dummy = 0,
    .bottom_dummy = 0,
  },
  .color_level_info =
  {
    .white_level = 1023,
    .r_pedestal = 1040,
    .gr_pedestal = 1040,
    .gb_pedestal = 1040,
    .b_pedestal = 1040,
  },
  .sensor_stream_info_array =
  {
    .sensor_stream_info =
    {
      {
        .vc_cfg_size = 1,
        .vc_cfg =
        {
          {
            .cid = 0,
            .dt = CSI_RAW10,
            .decode_format = CSI_DECODE_10BIT
          },
        },
        .pix_data_fmt =
        {
          SENSOR_BAYER,
        },
      },
    },
    .size = 1,
  },
  .start_settings =
  {
    .reg_setting_a = START_REG_ARRAY,
    .addr_type = CAMERA_I2C_WORD_ADDR,
    .data_type = CAMERA_I2C_BYTE_DATA,
    .delay = 0,
  },
  .stop_settings =
  {
    .reg_setting_a = STOP_REG_ARRAY,
    .addr_type = CAMERA_I2C_WORD_ADDR,
    .data_type = CAMERA_I2C_BYTE_DATA,
    .delay = 0,
  },
  .groupon_settings =
  {
    .reg_setting_a = GROUPON_REG_ARRAY,
    .addr_type = CAMERA_I2C_WORD_ADDR,
    .data_type = CAMERA_I2C_BYTE_DATA,
    .delay = 0,
  },
  .groupoff_settings =
  {
    .reg_setting_a = GROUPOFF_REG_ARRAY,
    .addr_type = CAMERA_I2C_WORD_ADDR,
    .data_type = CAMERA_I2C_BYTE_DATA,
    .delay = 0,
  },
  .test_pattern_info =
  {
    .test_pattern_settings =
    {
      {
        .mode = SENSOR_TEST_PATTERN_OFF,
        .settings =
        {
          .reg_setting_a =
           {
             {0x5040, 0x00, 0x00},
             {0x8008, 0x00, 0x00},
           },
          .addr_type = CAMERA_I2C_WORD_ADDR,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .delay = 0,
        },
      },
      {
        .mode = SENSOR_TEST_PATTERN_SOLID_COLOR,
        .settings =
        {
          .reg_setting_a = {{0x8008, 0x01, 0x00}},
          .addr_type = CAMERA_I2C_WORD_ADDR,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .delay = 0,
        },
      },
      {
        .mode = SENSOR_TEST_PATTERN_COLOR_BARS,
        .settings =
        {
          .reg_setting_a = {{0x5040, 0x80, 0x00}},
          .size = 1,
          .addr_type = CAMERA_I2C_WORD_ADDR,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .delay = 0,
        },
      },
      {
        .mode = SENSOR_TEST_PATTERN_PN9,
        .settings =
        {
          .reg_setting_a = {{0x8008, 0x02, 0x00}},
          .size = 1,
          .addr_type = CAMERA_I2C_WORD_ADDR,
          .data_type = CAMERA_I2C_BYTE_DATA,
          .delay = 0,
        },
      },
    },
    .size = 4,
    .solid_mode_addr =
    {
      .r_addr = 0x8006,
      .gr_addr = 0x8004,
      .gb_addr = 0x8002,
      .b_addr = 0x8000,
    },
  },
  .init_settings_array =
  {
    .reg_settings =
    {
      {
        .reg_setting_a = INIT0_REG_ARRAY,
        .addr_type = CAMERA_I2C_WORD_ADDR,
        .data_type = CAMERA_I2C_BYTE_DATA,
        .delay = 0,
      },
    },
    .size = 1,
  },
  .res_settings_array =
  {
    .reg_settings =
    {
      /* Res 0 */
      {
        .reg_setting_a = RES0_REG_ARRAY,
        .addr_type = CAMERA_I2C_WORD_ADDR,
        .data_type = CAMERA_I2C_BYTE_DATA,
        .delay = 0,
      },
      /* Res 1 */
      {
        .reg_setting_a = RES1_REG_ARRAY,
        .addr_type = CAMERA_I2C_WORD_ADDR,
        .data_type = CAMERA_I2C_BYTE_DATA,
        .delay = 0,
      },
    },
    .size = 2,
  },
  .out_info_array =
  {
    .out_info =
    {
      /* Res 0 */
      {
        .x_output = 1280,
        .y_output = 800,
        .line_length_pclk = 0x02d8,
        .frame_length_lines = 0x728,
        .vt_pixel_clk = 47884800,
        .op_pixel_clk = 48000000,
        .binning_factor = 1,
        .min_fps = 7.5,
        .max_fps = 30.0,
        .mode = SENSOR_DEFAULT_MODE,
        .offset_x = 0,
        .offset_y = 0,
        .scale_factor = 0,
      },
      /* Res 1 */
      {
        .x_output = 640,
        .y_output = 400,
        .line_length_pclk = 0x02d8,
        .frame_length_lines = 0x0e50,
        .vt_pixel_clk = 47884800,
        .op_pixel_clk = 48000000,
        .binning_factor = 2,
        .min_fps = 7.5,
        .max_fps = 30.0,
        .mode = SENSOR_DEFAULT_MODE,
        .offset_x = 0,
        .offset_y = 0,
        .scale_factor = 0,
      },
    },
    .size = 2,
  },
  .csi_params =
  {
    .lane_cnt = 1,
    .settle_cnt = 0x03,
    .is_csi_3phase = 0,
  },
  .csid_lut_params_array =
  {
    .lut_params =
    {
      /* Res 0 */
      {
        .num_cid = 1,
        .vc_cfg_a =
        {
          {
            .cid = 0,
            .dt = CSI_RAW10,
            .decode_format = CSI_DECODE_10BIT
          },
        },
      },
      /* Res 1 */
      {
        .num_cid = 1,
        .vc_cfg_a =
        {
          {
            .cid = 0,
            .dt = CSI_RAW10,
            .decode_format = CSI_DECODE_10BIT
          },
        },
      }
    },
    .size = 2,
  },
  .crop_params_array =
  {
    .crop_params =
    {
      /* Res 0 */
      {
        .top_crop = 0,
        .bottom_crop = 0,
        .left_crop = 0,
        .right_crop = 0,
      },
      /* Res 1 */
      {
        .top_crop = 0,
        .bottom_crop = 0,
        .left_crop = 0,
        .right_crop = 0,
      },
    },
    .size = 2,
  },
  .exposure_func_table =
  {
    .sensor_calculate_exposure = sensor_calculate_exposure,
    .sensor_fill_exposure_array = sensor_fill_exposure_array,
  },
  .meta_data_out_info_array =
  {
    .meta_data_out_info =
    {
      {
        .width = 0,
        .height = 0,
        .stats_type = 0,
      },
    },
    .size = 0,
  },
  .rolloff_config =
  {
    .enable = FALSE,
    .full_size_info =
    {
      .full_size_width = 0,
      .full_size_height = 0,
      .full_size_left_crop = 0,
      .full_size_top_crop = 0,
    },
  },
  .adc_readout_time = 0,
};

#endif
