#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting atreset: "
    start-stop-daemon -S -b -a /usr/bin/atfwd_quectel
    echo "done"
    ;;
  stop)
    echo -n "Stopping atreset: "
    start-stop-daemon -K -n /usr/bin/atfwd_quectel
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage atfwd_daemon{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
