/**
 * lc898212xd_qc2002_actuator.h
 *
 * DESCRIPTION
 *  Auto-Generated by Actuator tool.
 *
 * Copyright (c) 2015 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
  {
    .actuator_params =
    {
      .module_name = "onsemi",
      .actuator_name = "lc898212xd_qc2002",
      .i2c_addr = 0xE4,
      .i2c_freq_mode = SENSOR_I2C_MODE_FAST,
      .i2c_data_type = CAMERA_I2C_WORD_DATA,
      .i2c_addr_type = CAMERA_I2C_BYTE_ADDR,
      .act_type = ACTUATOR_TYPE_BIVCM,
      .data_size = 12,
      .reg_tbl =
      {
        .reg_tbl_size = 3,
        .reg_params =
        {
          {
            .reg_write_type = ACTUATOR_WRITE_DIR_REG,
            .reg_addr = 0x16,
            .data_type = CAMERA_I2C_WORD_DATA,
            .addr_type = CAMERA_I2C_BYTE_ADDR,
          },
          {
            .reg_write_type = ACTUATOR_WRITE_DAC,
            .hw_mask = 0x0000,
            .reg_addr = 0xA1,
            .hw_shift = 0,
            .data_shift = 4,
          },
          {
            .reg_write_type = ACTUATOR_WRITE,
            .reg_addr = 0x8A,
            .data_type = CAMERA_I2C_BYTE_DATA,
            .addr_type = CAMERA_I2C_BYTE_ADDR,
            .reg_data = 0xD,
          },
        },
      },
      .init_setting_size = 53,
      .init_settings =
      {
        {0x80,CAMERA_I2C_BYTE_ADDR,0x34  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x81,CAMERA_I2C_BYTE_ADDR,0x20  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x84,CAMERA_I2C_BYTE_ADDR,0xE0  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x87,CAMERA_I2C_BYTE_ADDR,0x05  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0xA4,CAMERA_I2C_BYTE_ADDR,0x24  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x3A,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x04,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x02,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x18,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x88,CAMERA_I2C_BYTE_ADDR,0x70  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x28,CAMERA_I2C_BYTE_ADDR,0x8080,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x4C,CAMERA_I2C_BYTE_ADDR,0x4000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x83,CAMERA_I2C_BYTE_ADDR,0xAC  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x85,CAMERA_I2C_BYTE_ADDR,0xC0  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x85,CAMERA_I2C_BYTE_ADDR,0x00  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_POLL, 100 },
        {0x84,CAMERA_I2C_BYTE_ADDR,0xE3  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x97,CAMERA_I2C_BYTE_ADDR,0x00  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x98,CAMERA_I2C_BYTE_ADDR,0x42  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x99,CAMERA_I2C_BYTE_ADDR,0x00  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x9A,CAMERA_I2C_BYTE_ADDR,0x00  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x86,CAMERA_I2C_BYTE_ADDR,0x40  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x40,CAMERA_I2C_BYTE_ADDR,0x4030,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x42,CAMERA_I2C_BYTE_ADDR,0x7150,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x44,CAMERA_I2C_BYTE_ADDR,0x8F90,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x46,CAMERA_I2C_BYTE_ADDR,0x61B0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x48,CAMERA_I2C_BYTE_ADDR,0x65B0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x4A,CAMERA_I2C_BYTE_ADDR,0x7FF0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x4C,CAMERA_I2C_BYTE_ADDR,0x4030,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x4E,CAMERA_I2C_BYTE_ADDR,0x8010,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x50,CAMERA_I2C_BYTE_ADDR,0x04F0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x52,CAMERA_I2C_BYTE_ADDR,0x7610,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x54,CAMERA_I2C_BYTE_ADDR,0x2030,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x56,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x58,CAMERA_I2C_BYTE_ADDR,0x7FF0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x5A,CAMERA_I2C_BYTE_ADDR,0x0800,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x5C,CAMERA_I2C_BYTE_ADDR,0x72F0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x5E,CAMERA_I2C_BYTE_ADDR,0x7F70,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x60,CAMERA_I2C_BYTE_ADDR,0x7ED0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x62,CAMERA_I2C_BYTE_ADDR,0x7FF0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x64,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x66,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x68,CAMERA_I2C_BYTE_ADDR,0x5130,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x6A,CAMERA_I2C_BYTE_ADDR,0x72F0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x6C,CAMERA_I2C_BYTE_ADDR,0x8010,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x6E,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x70,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x72,CAMERA_I2C_BYTE_ADDR,0x18E0,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x74,CAMERA_I2C_BYTE_ADDR,0x4E30,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x30,CAMERA_I2C_BYTE_ADDR,0x0000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x76,CAMERA_I2C_BYTE_ADDR,0x3050,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x78,CAMERA_I2C_BYTE_ADDR,0x2000,CAMERA_I2C_WORD_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x86,CAMERA_I2C_BYTE_ADDR,0x60  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
        {0x87,CAMERA_I2C_BYTE_ADDR,0x85  ,CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
      },
      .deinit_setting_size = 1,
      .deinit_settings =
      {
        { 0x84, CAMERA_I2C_BYTE_ADDR,
          0x00, CAMERA_I2C_BYTE_DATA, ACTUATOR_I2C_OP_WRITE, 0 },
      },
    }, /* actuator_params */

    .actuator_tuned_params =
    {
      .scenario_size =
      {
        1, /* MOVE_NEAR */
        1, /* MOVE_FAR */
      },
      .ringing_scenario =
      {
        /* MOVE_NEAR */
        {
          1023,
        },
        /* MOVE_FAR */
        {
          1023,
        },
      },
      .initial_code = 0,
      .region_size = 1,
      .region_params =
      {
        {
          .step_bound =
          {
            1023, /* Macro step boundary*/
            0, /* Infinity step boundary*/
          },
          .code_per_step = 1,
          .qvalue = 128,
        },
      },
      /* damping used as direction value */
      .damping =
      {
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0xFFF,
                .damping_delay = 1000,
                .hw_params = 0x0000040,
              },
            },
          },
        },
        /* damping[MOVE_FAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0xFFF,
                .damping_delay = 1000,
                .hw_params = 0x0000FFc0,
              },
            },
          },
        },
      },
    }, /* actuator_tuned_params */
  },
