/* csv1: 14BF3C3B */
//=============================================================================
//                          C H R O M A T I X
//
//   DESCRIPTION
//   Auto-Generated by Chromatix tool defining camera tunable parameters.
//
// Copyright (c) 2017 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
//=============================================================================

/* Header Version Info */
{
   0x0309, /* Chromatix Version */
   0, /* Revision */
   /* Chromatix App Version */
   {
      6, /* Major */
      16, /* Minor */
      5, /* Revision */
      1, /* Build */
   },
   HEADER_COMMON, /* Header Type */
   0, /* Is Compressed */
   0, /* Is Mono */
   0, /* Is Video */
   0, /* Reserved Align */
   MODE_UNKNOWN, /* Chromatix Mode */
   0, /* Target ID */
   0, /* Chromatix ID */
   /* Reserved */
   {
      0, 0, 0, 0
   }
},

/******************************************************************************/
// Feature name : Iot.
/******************************************************************************/
{
   {
      0,
   },
   {
      0,
   },
},
/******************************************************************/
