#! /bin/sh
# Copyright (c) 2016-2017, Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# Copyright (c) 2015 The Linux Foundation. All rights reserved.
#

#
# Function to start sensors for SSC enabled platforms
#

set -e
export KERNEL=`uname -r`

case "$1" in
    start)
        echo -n "Starting sensor daemon: "
        start-stop-daemon -S -b -a /usr/bin/sensors.qcom
        echo "done"
        ;;
    stop)
        echo -n "Stopping sensor daemon: "
        start-stop-daemon -K -n sensors.qcom
        echo "done"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage sensors.qcom { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
