#ifndef _CSR_SYNERGY_BT_CONFIG_GLOBAL_H
#define _CSR_SYNERGY_BT_CONFIG_GLOBAL_H

/******************************************************************************
 Copyright (c) 2011-2018 Qualcomm Technologies International, Ltd.
 All Rights Reserved.
 Qualcomm Technologies International, Ltd. Confidential and Proprietary.

REVISION:      $Revision: #2 $
******************************************************************************/

#ifdef __cplusplus
    extern "C" {
#endif

/* BlueStack on host */
#undef BUILD_FOR_HOST /* This is needed because some compilers are not able to compare command-line
                         defines to defines in the header files. */
#define BUILD_FOR_HOST 

        

#undef DM_ACL_DUMP_DEBUG
#undef INSTALL_VM_MODULE
#undef INSTALL_DM_POWERSTATES_MODULE
#undef INSTALL_L2CAP_CRC
#undef INSTALL_L2CAP_ROUTER_SUPPORT
#undef INSTALL_L2CAP_UCD_SUPPORT
#undef L2CAP_HCI_DATA_CREDIT_CHECKS
#undef L2CAP_HCI_DATA_CREDIT_CHECKS_PANIC
#undef L2CAP_HCI_DATA_CREDIT_SLOW_CHECKS

/* This is needed because some compilers are not able to compare command-line
                         defines to defines in the header files. */
#ifdef EXCLUDE_CSR_BT_THERM_SRV_MODULE
#undef EXCLUDE_CSR_BT_THERM_SRV_MODULE
#define EXCLUDE_CSR_BT_THERM_SRV_MODULE
#endif
#ifdef EXCLUDE_CSR_BT_PROX_SRV_MODULE
#undef EXCLUDE_CSR_BT_PROX_SRV_MODULE
#define EXCLUDE_CSR_BT_PROX_SRV_MODULE
#endif
#ifdef EXCLUDE_CSR_BT_PPP_MODULE
#undef EXCLUDE_CSR_BT_PPP_MODULE
#define EXCLUDE_CSR_BT_PPP_MODULE
#endif
#ifdef CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#undef CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH 
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#endif
#ifdef CSR_BT_INSTALL_BSL_MODULE 
#undef CSR_BT_INSTALL_BSL_MODULE 
#define CSR_BT_INSTALL_BSL_MODULE
#endif
#ifdef CSR_BT_INSTALL_CM_GET_LINK_QUALITY 
#undef CSR_BT_INSTALL_CM_GET_LINK_QUALITY 
#define CSR_BT_INSTALL_CM_GET_LINK_QUALITY
#endif
#ifdef CSR_BT_INSTALL_CM_READ_COD 
#undef  CSR_BT_INSTALL_CM_READ_COD 
#define CSR_BT_INSTALL_CM_READ_COD
#endif
#ifdef CSR_BT_INSTALL_CM_READ_LOCAL_NAME 
#undef  CSR_BT_INSTALL_CM_READ_LOCAL_NAME 
#define CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#endif
#ifdef CSR_BT_INSTALL_CM_READ_RSSI 
#undef  CSR_BT_INSTALL_CM_READ_RSSI 
#define CSR_BT_INSTALL_CM_READ_RSSI
#endif
#ifdef CSR_BT_INSTALL_CM_READ_SCAN_EANBLE 
#undef CSR_BT_INSTALL_CM_READ_SCAN_EANBLE 
#define CSR_BT_INSTALL_CM_READ_SCAN_EANBLE
#endif
#ifdef CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL 
#undef  CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#define CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#endif
#ifdef CSR_BT_INSTALL_CM_DUT_MODE 
#undef  CSR_BT_INSTALL_CM_DUT_MODE
#define CSR_BT_INSTALL_CM_DUT_MODE
#endif
#ifdef CSR_BT_INSTALL_CM_CONNECTABLE 
#undef  CSR_BT_INSTALL_CM_CONNECTABLE
#define CSR_BT_INSTALL_CM_CONNECTABLE
#endif
#ifdef CSR_BT_INSTALL_CM_WRITE_PAGE_TO 
#undef  CSR_BT_INSTALL_CM_WRITE_PAGE_TO
#define CSR_BT_INSTALL_CM_WRITE_PAGE_TO
#endif
#ifdef CSR_BT_INSTALL_CM_WRITE_PAGE_SCAN 
#undef  CSR_BT_INSTALL_CM_WRITE_PAGE_SCAN
#define CSR_BT_INSTALL_CM_WRITE_PAGE_SCAN
#endif
#ifdef CSR_BT_INSTALL_CM_WRITE_INQUIRY_SCAN_TYPE 
#undef  CSR_BT_INSTALL_CM_WRITE_INQUIRY_SCAN_TYPE
#define CSR_BT_INSTALL_CM_WRITE_INQUIRY_SCAN_TYPE
#endif
#ifdef CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES 
#undef  CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES
#define CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES
#endif
#ifdef CSR_BT_INSTALL_CM_AFH 
#undef  CSR_BT_INSTALL_CM_AFH
#define CSR_BT_INSTALL_CM_AFH
#endif
#ifdef CSR_BT_INSTALL_CM_READ_CLOCK
#undef  CSR_BT_INSTALL_CM_READ_CLOCK
#define CSR_BT_INSTALL_CM_READ_CLOCK
#endif
#ifdef CSR_BT_INSTALL_CM_LINK_POLICY
#undef  CSR_BT_INSTALL_CM_LINK_POLICY
#define CSR_BT_INSTALL_CM_LINK_POLICY
#endif
#ifdef CSR_BT_INSTALL_CM_EIR_FLAGS
#undef  CSR_BT_INSTALL_CM_EIR_FLAGS
#define CSR_BT_INSTALL_CM_EIR_FLAGS
#endif
#ifdef CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG
#undef  CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG
#define CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG
#endif
#ifdef CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#undef  CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#define CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#endif
#ifdef CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#undef  CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#define CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#endif
#ifdef CSR_BT_INSTALL_CM_LOW_POWER_CONFIG_PUBLIC
#undef  CSR_BT_INSTALL_CM_LOW_POWER_CONFIG_PUBLIC
#define CSR_BT_INSTALL_CM_LOW_POWER_CONFIG_PUBLIC
#endif

#ifdef CSR_BT_INSTALL_CM_WRITE_COD
#undef  CSR_BT_INSTALL_CM_WRITE_COD
#define CSR_BT_INSTALL_CM_WRITE_COD
#endif
#ifdef CSR_BT_INSTALL_CM_WRITE_LINK_SUPERVISION_TIMEOUT
#undef  CSR_BT_INSTALL_CM_WRITE_LINK_SUPERVISION_TIMEOUT
#define CSR_BT_INSTALL_CM_WRITE_LINK_SUPERVISION_TIMEOUT
#endif
#ifdef CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#undef  CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#define CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#endif
#ifdef CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#undef CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#define CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#endif
#ifdef CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#undef  CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#define CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#endif
#ifdef CSR_BT_INSTALL_L2CAP_MODULE
#undef  CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_L2CAP_MODULE
#endif
#ifdef CSR_BT_INSTALL_MDER_MODULE
#undef  CSR_BT_INSTALL_MDER_MODULE
#define CSR_BT_INSTALL_MDER_MODULE
#endif
#ifdef CSR_BT_INSTALL_OBEX_COMMON_CALLBACK
#undef  CSR_BT_INSTALL_OBEX_COMMON_CALLBACK
#define CSR_BT_INSTALL_OBEX_COMMON_CALLBACK
#endif
#ifdef CSR_BT_INSTALL_OBEX_SERVICE_DISCONNECT
#undef CSR_BT_INSTALL_OBEX_SERVICE_DISCONNECT
#define CSR_BT_INSTALL_OBEX_SERVICE_DISCONNECT
#endif
#ifdef CSR_BT_INSTALL_OBEX_CLI_GET
#undef  CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_GET
#endif
#ifdef CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#undef  CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#endif
#ifdef CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#undef  CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#define CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#endif
#ifdef CSR_BT_INSTALL_OBEX_CONTEXT_ID 
#undef CSR_BT_INSTALL_OBEX_CONTEXT_ID 
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#endif
#ifdef CSR_BT_INSTALL_OBEX_ERROR_CHECK
#undef  CSR_BT_INSTALL_OBEX_ERROR_CHECK
#define CSR_BT_INSTALL_OBEX_ERROR_CHECK
#endif
#ifdef CSR_BT_INSTALL_OBEX_GOEP_20
#undef CSR_BT_INSTALL_OBEX_GOEP_20 
#define CSR_BT_INSTALL_OBEX_GOEP_20
#endif
#ifdef CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#undef  CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#endif
#ifdef CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#undef  CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#endif
#ifdef CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#undef  CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#endif
#ifdef CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#undef  CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#ifdef CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#undef  CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#define CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#endif
#ifdef CSR_BT_INSTALL_OBEX_SRV_GET
#undef  CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_GET
#endif
#ifdef CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#undef  CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#endif
#ifdef CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#undef  CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#define CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#endif
#ifdef CSR_BT_INSTALL_OBEX_STRING_DESCRIPTION 
#undef  CSR_BT_INSTALL_OBEX_STRING_DESCRIPTION 
#define CSR_BT_INSTALL_OBEX_STRING_DESCRIPTION
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET 
#undef  CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET 
#define CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET 
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_COPY_IMAGE 
#undef  CSR_BT_INSTALL_OBEX_UTIL_COPY_IMAGE 
#define CSR_BT_INSTALL_OBEX_UTIL_COPY_IMAGE
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_CREATE_NAME
#undef  CSR_BT_INSTALL_OBEX_UTIL_CREATE_NAME
#define CSR_BT_INSTALL_OBEX_UTIL_CREATE_NAME
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_GET_LENGTH
#undef  CSR_BT_INSTALL_OBEX_UTIL_GET_LENGTH
#define CSR_BT_INSTALL_OBEX_UTIL_GET_LENGTH
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#undef  CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#undef  CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#undef  CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#endif

#ifdef CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET 
#undef  CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET 
#define CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET 
#endif
#ifdef CSR_BT_INSTALL_OBEX_UTIL_XML
#undef  CSR_BT_INSTALL_OBEX_UTIL_XML
#define CSR_BT_INSTALL_OBEX_UTIL_XML
#endif
#ifdef CSR_BT_INSTALL_OBEX_UNREGISTER_SDP_RECORD_ON_CONN
#undef CSR_BT_INSTALL_OBEX_UNREGISTER_SDP_RECORD_ON_CONN
#define CSR_BT_INSTALL_OBEX_UNREGISTER_SDP_RECORD_ON_CONN
#endif
#ifdef CSR_BT_INSTALL_OPC_GET 
#undef  CSR_BT_INSTALL_OPC_GET 
#define CSR_BT_INSTALL_OPC_GET
#endif
#ifdef CSR_BT_INSTALL_OPS_GET 
#undef  CSR_BT_INSTALL_OPS_GET 
#define CSR_BT_INSTALL_OPS_GET 
#endif
#ifdef CSR_BT_INSTALL_RFC_MODULE
#undef  CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#endif
#ifdef CSR_BT_INSTALL_SC_AUTHENTICATE
#undef  CSR_BT_INSTALL_SC_AUTHENTICATE
#define CSR_BT_INSTALL_SC_AUTHENTICATE
#endif
#ifdef CSR_BT_INSTALL_SC_ENCRYPTION
#undef  CSR_BT_INSTALL_SC_ENCRYPTION
#define CSR_BT_INSTALL_SC_ENCRYPTION
#endif
#ifdef CSR_BT_INSTALL_SC_OOB
#undef CSR_BT_INSTALL_SC_OOB
#define CSR_BT_INSTALL_SC_OOB
#endif
#ifdef CSR_BT_INSTALL_SC_SET_EVENT_MASK
#undef CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#endif
#ifdef CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#undef CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#endif
#ifdef CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#undef CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#endif
#ifdef CSR_BT_INSTALL_SC_MODE
#undef CSR_BT_INSTALL_SC_MODE
#define CSR_BT_INSTALL_SC_MODE
#endif
#ifdef CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#undef CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#endif
#ifdef CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#undef CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#endif

#ifdef CSR_BT_INSTALL_SCO_MODULE
#undef  CSR_BT_INSTALL_SCO_MODULE
#define CSR_BT_INSTALL_SCO_MODULE
#endif
#ifdef CSR_BT_INSTALL_SPP_EXTENDED
#undef  CSR_BT_INSTALL_SPP_EXTENDED
#ifdef CSR_USE_BLUECORE_CHIP
#define CSR_BT_INSTALL_SPP_EXTENDED
#endif
#endif
#ifdef INSTALL_AMP_SUPPORT
#undef  INSTALL_AMP_SUPPORT
#define INSTALL_AMP_SUPPORT
#endif
#ifdef INSTALL_ATT_BREDR
#undef  INSTALL_ATT_BREDR
#define INSTALL_ATT_BREDR
#endif
#ifdef INSTALL_ATT_MODULE
#undef  INSTALL_ATT_MODULE
#define INSTALL_ATT_MODULE
#endif
#ifdef INSTALL_CPRP
#undef INSTALL_CPRP
#define INSTALL_CPRP
#endif
#ifdef INSTALL_SIFE
#undef INSTALL_SIFE
#define INSTALL_SIFE
#endif
#ifdef INSTALL_DM_SYNC_MODULE
#undef  INSTALL_DM_SYNC_MODULE
#define INSTALL_DM_SYNC_MODULE
#endif
#ifdef INSTALL_L2CAP_CONNLESS_SUPPORT
#undef  INSTALL_L2CAP_CONNLESS_SUPPORT
#define INSTALL_L2CAP_CONNLESS_SUPPORT
#endif
#ifdef INSTALL_L2CAP_DEBUG
#undef  INSTALL_L2CAP_DEBUG
#define INSTALL_L2CAP_DEBUG
#endif
#ifdef INSTALL_L2CAP_ENHANCED_SUPPORT
#undef  INSTALL_L2CAP_ENHANCED_SUPPORT
#define INSTALL_L2CAP_ENHANCED_SUPPORT
#endif
#ifdef INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#undef  INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#endif
#ifdef INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#undef  INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#endif
#ifdef INSTALL_L2CAP_FLOWSPEC_SUPPORT
#undef  INSTALL_L2CAP_FLOWSPEC_SUPPORT
#define INSTALL_L2CAP_FLOWSPEC_SUPPORT
#endif
#ifdef INSTALL_L2CAP_MODULE
#undef  INSTALL_L2CAP_MODULE
#define INSTALL_L2CAP_MODULE
#endif
#ifdef INSTALL_L2CAP_QOS_SUPPORT 
#undef  INSTALL_L2CAP_QOS_SUPPORT 
#define INSTALL_L2CAP_QOS_SUPPORT 
#endif
#ifdef INSTALL_PAN_MODULE
#undef  INSTALL_PAN_MODULE
#define INSTALL_PAN_MODULE
#endif
#ifdef INSTALL_RFCOMM_MODULE
#undef  INSTALL_RFCOMM_MODULE
#define INSTALL_RFCOMM_MODULE
#endif
#ifdef INSTALL_SDP_MODULE
#undef  INSTALL_SDP_MODULE
#define INSTALL_SDP_MODULE
#endif
#ifdef INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#undef INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#define INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#endif
#ifdef INSTALL_BREDR_SECURE_CONNECTIONS
#undef INSTALL_BREDR_SECURE_CONNECTIONS
#define INSTALL_BREDR_SECURE_CONNECTIONS
#endif
#ifdef INSTALL_BREDR_PING
#undef INSTALL_BREDR_PING
#define INSTALL_BREDR_PING
#endif
#ifdef INSTALL_SC_ESCO_PARAMS_REWRITE
#undef INSTALL_SC_ESCO_PARAMS_REWRITE
#define INSTALL_SC_ESCO_PARAMS_REWRITE
#endif
#ifdef INSTALL_SM_MODULE
#undef  INSTALL_SM_MODULE
#define INSTALL_SM_MODULE
#endif
#ifdef INSTALL_SM_LE_SECURE_CONNECTIONS
#undef INSTALL_SM_LE_SECURE_CONNECTIONS
#define INSTALL_SM_LE_SECURE_CONNECTIONS
#endif
#ifdef INSTALL_SM_PRIVACY_1P2
#undef INSTALL_SM_PRIVACY_1P2
#define INSTALL_SM_PRIVACY_1P2
#endif
#ifdef INSTALL_SM_PRIVACY_1P2_DUMMY_DEVICE_IN_RL
#undef INSTALL_SM_PRIVACY_1P2_DUMMY_DEVICE_IN_RL
#define INSTALL_SM_PRIVACY_1P2_DUMMY_DEVICE_IN_RL
#endif
#ifdef INSTALL_GAP_SC_ONLY_MODE
#undef INSTALL_GAP_SC_ONLY_MODE
#define INSTALL_GAP_SC_ONLY_MODE
#endif
#ifdef INSTALL_LE_PING
#undef INSTALL_LE_PING
#define INSTALL_LE_PING
#endif
#ifdef INSTALL_KEYPRESS_NOTIFICATION
#undef INSTALL_KEYPRESS_NOTIFICATION
#define INSTALL_KEYPRESS_NOTIFICATION
#endif
#ifdef DISABLE_SM_CROSS_TRNSPT_KEY_DERIVATION
#undef DISABLE_SM_CROSS_TRNSPT_KEY_DERIVATION
#define DISABLE_SM_CROSS_TRNSPT_KEY_DERIVATION
#endif
#ifdef INSTALL_ULP
#undef  INSTALL_ULP
#define INSTALL_ULP
#endif
#ifdef CSR_BT_INSTALL_SDC_SET_PORT_PAR
#undef CSR_BT_INSTALL_SDC_SET_PORT_PAR
#define CSR_BT_INSTALL_SDC_SET_PORT_PAR
#endif
#ifdef CSR_BT_INSTALL_UTIL_UCS2
#undef CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_UTIL_UCS2
#endif
#ifdef CSR_BT_INSTALL_OPTIONAL_UTIL
#undef CSR_BT_INSTALL_OPTIONAL_UTIL
#define CSR_BT_INSTALL_OPTIONAL_UTIL
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_IAC
#undef CSR_BT_INSTALL_CM_PRI_IAC
#define CSR_BT_INSTALL_CM_PRI_IAC
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_SDC
#undef CSR_BT_INSTALL_CM_PRI_SDC
#define CSR_BT_INSTALL_CM_PRI_SDC
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE
#undef CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE
#define CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH
#undef CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH
#define CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_CONNECT_EXT
#undef CSR_BT_INSTALL_CM_PRI_CONNECT_EXT
#define CSR_BT_INSTALL_CM_PRI_CONNECT_EXT
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_SCO_RENEGOTIATE
#undef CSR_BT_INSTALL_CM_PRI_SCO_RENEGOTIATE
#define CSR_BT_INSTALL_CM_PRI_SCO_RENEGOTIATE
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_MODE_SETTINGS
#undef CSR_BT_INSTALL_CM_PRI_MODE_SETTINGS
#define CSR_BT_INSTALL_CM_PRI_MODE_SETTINGS
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#undef CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#define CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB
#undef CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB
#define CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_L2CA_DATA_ABORT
#undef CSR_BT_INSTALL_CM_PRI_L2CA_DATA_ABORT
#define CSR_BT_INSTALL_CM_PRI_L2CA_DATA_ABORT
#endif
#ifdef CSR_BT_INSTALL_CM_PRI_SET_EVENT_FILTER_BDADDR
#undef CSR_BT_INSTALL_CM_PRI_SET_EVENT_FILTER_BDADDR
#define CSR_BT_INSTALL_CM_PRI_SET_EVENT_FILTER_BDADDR
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_SYNCHRONOUS_CONNECTION
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_SYNCHRONOUS_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_SYNCHRONOUS_CONNECTION
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ROLE_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ROLE_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ROLE_CHANGE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_MODE_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_MODE_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_MODE_CHANGE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LSTO_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LSTO_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LSTO_CHANGE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_CHANNEL_TYPE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_CHANNEL_TYPE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_CHANNEL_TYPE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_EXT_SYNC_CONNECTION
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_EXT_SYNC_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_EXT_SYNC_CONNECTION
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_FEATURES
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_FEATURES
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_FEATURES
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_VERSION
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_VERSION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_VERSION
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_A2DP_BIT_RATE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_A2DP_BIT_RATE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_A2DP_BIT_RATE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_INQUIRY_PAGE_STATE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_INQUIRY_PAGE_STATE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_INQUIRY_PAGE_STATE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ENCRYPT_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ENCRYPT_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ENCRYPT_CHANGE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_HIGH_PRIORITY_DATA
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_HIGH_PRIORITY_DATA
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_HIGH_PRIORITY_DATA
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_DEINITIALIZED
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_DEINITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_DEINITIALIZED
#endif
#ifdef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE
#undef CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE
#endif

#ifdef CSR_BT_INSTALL_SD_SEARCH_CONFIG
#undef CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define CSR_BT_INSTALL_SD_SEARCH_CONFIG
#endif
#ifdef CSR_BT_INSTALL_SD_MEMORY_CONFIG
#undef CSR_BT_INSTALL_SD_MEMORY_CONFIG
#define CSR_BT_INSTALL_SD_MEMORY_CONFIG
#endif

#ifdef CSR_BT_INSTALL_HF_CONFIG_AUDIO
#undef CSR_BT_INSTALL_HF_CONFIG_AUDIO
#define CSR_BT_INSTALL_HF_CONFIG_AUDIO
#endif

#ifdef CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#undef CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#define CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#endif
#ifdef CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#undef CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#define CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#endif
#ifdef CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#undef CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#define CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#endif

#ifdef CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#undef CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#define CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#endif

#ifdef CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#undef CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#define CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#endif

#ifdef CSR_BT_INSTALL_SC_SECURITY_MODE
#undef CSR_BT_INSTALL_SC_SECURITY_MODE
#define CSR_BT_INSTALL_SC_SECURITY_MODE
#endif

#ifdef CSR_BT_INSTALL_SC_TRUST_LEVEL
#undef CSR_BT_INSTALL_SC_TRUST_LEVEL
#define CSR_BT_INSTALL_SC_TRUST_LEVEL
#endif

#ifdef CSR_BT_INSTALL_SC_CONFIG_MASK
#undef CSR_BT_INSTALL_SC_CONFIG_MASK
#define CSR_BT_INSTALL_SC_CONFIG_MASK
#endif

#ifdef CSR_BT_INSTALL_SC_DEBUG_MODE
#undef CSR_BT_INSTALL_SC_DEBUG_MODE
#define CSR_BT_INSTALL_SC_DEBUG_MODE
#endif

#ifdef CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#undef CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#define CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#endif

#ifdef CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#undef CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#define CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#endif

#ifdef CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#undef CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#define CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#endif

#ifdef CSR_BT_INSTALL_AVRCP_13_AND_HIGHER
#undef CSR_BT_INSTALL_AVRCP_13_AND_HIGHER
#define CSR_BT_INSTALL_AVRCP_13_AND_HIGHER
#endif

#ifdef CSR_BT_INSTALL_AVRCP_CT_COVER_ART
#undef CSR_BT_INSTALL_AVRCP_CT_COVER_ART
#define CSR_BT_INSTALL_AVRCP_CT_COVER_ART
#endif

#ifdef CSR_BT_INSTALL_AVRCP_TG_COVER_ART
#undef CSR_BT_INSTALL_AVRCP_TG_COVER_ART
#define CSR_BT_INSTALL_AVRCP_TG_COVER_ART
#endif

#ifdef CSR_BT_INSTALL_AVRCP_COVER_ART
#undef CSR_BT_INSTALL_AVRCP_COVER_ART
#define CSR_BT_INSTALL_AVRCP_COVER_ART
#endif

#ifdef INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#undef INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#define INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif


/* ---------- General Blue Stack flags ---------- */

#ifdef CSR_BT_BLUE_STACK_DEBUG
#define SM_DEBUG_PAIRING_SANITY
#define DM_ACL_DEBUG
#define INSTALL_L2CAP_DEBUG
#endif

#ifndef INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#define INSTALL_MULTIPLE_EXTENDED_FEATURES_PAGES
#endif

#ifndef INSTALL_BREDR_SECURE_CONNECTIONS
#define INSTALL_BREDR_SECURE_CONNECTIONS
#endif

#ifndef INSTALL_BREDR_PING
#define INSTALL_BREDR_PING
#endif

#ifndef INSTALL_SC_ESCO_PARAMS_REWRITE
#define INSTALL_SC_ESCO_PARAMS_REWRITE
#endif

#ifdef CSR_BT_SC_ONLY_MODE_ENABLE
#define INSTALL_GAP_SC_ONLY_MODE
#endif

/* L2CAP mandatory settings */
#define INSTALL_L2CAP_MODULE
#define INSTALL_L2CAP_ENHANCED_SUPPORT

#define INSTALL_L2CAP_QOS_SUPPORT 

/* SDP mandatory settings */
#define INSTALL_SDP_MODULE
#undef INSTALL_SDP_STATIC_SERVICE_RECORD_SUPPORT

/* SC mandatory settings */
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION

/* ---------- Core stack FSM-flags----------- */
#ifdef CSR_BT_INSTALL_L2CAP_CONNLESS_SUPPORT
#define INSTALL_L2CAP_CONNLESS_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#endif


#ifndef CSR_AMP_ENABLE
#define DISABLE_AMP_FSM_SUPPORT /* Used only by AMP */
#if !defined(CSR_BT_LE_ENABLE) && !defined(INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT)
#define DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT /* Used by LE, AMP */
#endif
#endif


/* ---------- Profile dependent flags ---------- */

/* AMP mandatory settings */
#ifdef CSR_AMP_ENABLE
#define CSR_BT_INSTALL_L2CAP_MODULE
#define INSTALL_AMP_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#define INSTALL_L2CAP_FLOWSPEC_SUPPORT
#define CSR_BT_INSTALL_CM_AFH
#else
#define EXCLUDE_CSR_BT_AMPM_MODULE
#endif /* CSR_AMP_ENABLE */


/* BLE mandatory settings */
#ifdef CSR_BT_LE_ENABLE
#define CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE
#define BUILD_FOR_HOST_FOR_ENCRYPTION_ATT_RACE
#define USB_ACL_DATA_FIX
#define INSTALL_ULP
#define INSTALL_ATT_MODULE
#define INSTALL_ATT_BREDR
#define INSTALL_L2CAP_FIXED_CHANNEL_BASE_SUPPORT
#define INSTALL_L2CAP_FIXED_CHANNEL_SUPPORT
#define INSTALL_SM_MODULE
#ifdef CSR_BT_INSTALL_LE_PRIVACY_1P2_SUPPORT
#define INSTALL_SM_PRIVACY_1P2
#define INSTALL_SM_PRIVACY_1P2_DUMMY_DEVICE_IN_RL
#endif
#ifdef CSR_BT_INSTALL_LESC_SUPPORT
#define INSTALL_SM_LE_SECURE_CONNECTIONS
#define INSTALL_LE_PING
#define INSTALL_KEYPRESS_NOTIFICATION
#endif
#ifdef CSR_BT_INSTALL_CTKD_SUPPORT
#ifndef CSR_BT_DISABLE_H7_CTKD
#define INSTALL_SM_LE_SECURE_CONNECTIONS_H7
#endif
#else
#define DISABLE_SM_CROSS_TRNSPT_KEY_DERIVATION
#endif
#define SM_HAS_FUNCTION_FOR_RAND
#define INSTALL_CPRP
#define INSTALL_SIFE
#ifndef EXCLUDE_CSR_BT_GATT_MODULE_OPTIONAL
#define CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#endif
#ifndef EXCLUDE_CSR_BT_PROX_SRV_MODULE
#define CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#endif
#ifndef EXCLUDE_CSR_BT_THERM_SRV_MODULE
#endif

#ifdef CSR_USE_QCA_CHIP 
/* [QTI] QCA chip can support BLE buffer, different from CSR BlueCore.
   This can be confirmed through "HCI_LE_Read_Buffer_Size". 
   E.g. QCA6174: Buffer Size (64 byte), Total Num LE Data Packets (16) */
#define SUPPORT_SEPARATE_LE_BUFFERS
#endif

#else /* CSR_BT_LE_ENABLE */
#define CSR_BT_EXCLUDE_SET_BLE_CONNECTION_PARAMETERS
#define CSR_BT_EXCLUDE_SM_SECURITY
#define EXCLUDE_CSR_BT_ATT_MODULE
#define EXCLUDE_CSR_BT_GATT_MODULE
#define EXCLUDE_CSR_BT_GATT_PRIVATE_MODULE
#define EXCLUDE_CSR_BT_THERM_SRV_MODULE
#define EXCLUDE_CSR_BT_PROX_SRV_MODULE
#endif /* CSR_BT_LE_ENABLE */



#ifndef EXCLUDE_CSR_BT_AVRCP_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#ifndef EXCLUDE_CSR_BT_AVRCP_MODULE_OPTIONAL
#ifndef EXCLUDE_CSR_BT_AVRCP_CT_MODULE
#define CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#define CSR_BT_INSTALL_AVRCP_13_AND_HIGHER
#ifndef EXCLUDE_CSR_BT_AVRCP_MODULE_COVER_ART
#define CSR_BT_INSTALL_AVRCP_COVER_ART
#define CSR_BT_INSTALL_AVRCP_CT_COVER_ART
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_UTIL_XML

/* Obex features required by CT Cover Art */
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
/*
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
*/
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
/*
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
*/

#define CSR_BT_INSTALL_OBEX_COMMON_CALLBACK
#define CSR_BT_INSTALL_OBEX_SERVICE_DISCONNECT

#endif /* EXCLUDE_CSR_BT_AVRCP_MODULE_COVER_ART */
#endif
#ifndef EXCLUDE_CSR_BT_AVRCP_TG_MODULE
#define CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#define CSR_BT_INSTALL_AVRCP_13_AND_HIGHER
#ifndef EXCLUDE_CSR_BT_AVRCP_MODULE_COVER_ART
#define CSR_BT_INSTALL_AVRCP_COVER_ART
#define CSR_BT_INSTALL_AVRCP_TG_COVER_ART
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_UTIL_XML

#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#define CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET
#endif /* EXCLUDE_CSR_BT_AVRCP_MODULE_COVER_ART */
#endif
#endif
#endif


#ifndef EXCLUDE_CSR_BT_AV_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#ifndef EXCLUDE_CSR_BT_AV_OPTIONAL
#define CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#endif
#endif


#ifndef EXCLUDE_CSR_BT_HF_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_SCO_MODULE
#ifndef EXCLUDE_CSR_BT_HF_MODULE_OPTIONAL
#define CSR_BT_INSTALL_HF_CONFIG_AUDIO
#endif
#endif


#ifndef EXCLUDE_CSR_BT_HFG_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_SCO_MODULE
#define CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#ifndef EXCLUDE_CSR_BT_HFG_MODULE_OPTIONAL
#define CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#define CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#define CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#endif
#endif

#ifndef EXCLUDE_CSR_BT_DG_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_DUNC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_SDC_SET_PORT_PAR
#endif

#ifndef EXCLUDE_CSR_BT_AT_MODULE 
/* Requiers DG_MODULE */
#endif



/*******  OBEX PROFILES ********/

#ifndef EXCLUDE_CSR_BT_OPC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#ifndef EXCLUDE_CSR_BT_OPC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OPC_GET /* Optional OPC feature */
#endif                                 
#ifdef CSR_BT_INSTALL_OPC_GET
#define CSR_BT_INSTALL_OBEX_CLI_GET
#endif
#endif

#ifndef EXCLUDE_CSR_BT_OPS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_UTIL_UCS2
#ifndef EXCLUDE_CSR_BT_OPS_MODULE_OPTIONAL 
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OPS_GET /* Mandetory OPS feature - If this is not defined an 
                                 OPC-get req will recieve a NOT_FOUND response. */
#endif
#endif


#ifndef EXCLUDE_CSR_BT_BIPC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_UTIL_XML /* Only used by BIP/BPP APP */
#define CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET /* BIPC & BIPS only */
#define CSR_BT_INSTALL_OBEX_UTIL_COPY_IMAGE /* BIPC only */
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET /* BIPC & BPPS only */
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_OBEX_STRING_DESCRIPTION /* BIP app only */
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#endif


#ifndef EXCLUDE_CSR_BT_BIPS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_CLI_GET 
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_UTIL_XML /* Only used by BIP/BPP APP */
#define CSR_BT_INSTALL_OBEX_UTIL_IMG_OFFSET /* BIPC & BIPS only */
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_OBEX_STRING_DESCRIPTION /* BIP app only */
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_USER_DEFINE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#endif


#ifndef EXCLUDE_CSR_BT_BPPS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_UTIL_XML /* Only used by BIP/BPP APP */
#define CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET /* BIPC & BPPS only */
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#ifndef EXCLUDE_CSR_BT_BPPS_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_CLI_GET /* Optional*/
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#endif
#endif


#ifndef EXCLUDE_CSR_BT_BPPC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_UTIL_XML /* Only used by BIP/BPP APP */
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#ifndef EXCLUDE_CSR_BT_BPPC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_CLI_GET /* Optional*/
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#endif
#endif


#ifndef EXCLUDE_CSR_BT_FTC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#ifndef EXCLUDE_CSR_BT_FTC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif

#ifndef EXCLUDE_CSR_BT_FTS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_UTIL_CREATE_NAME
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#ifndef EXCLUDE_CSR_BT_FTS_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif


#ifndef EXCLUDE_CSR_BT_PAC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#define CSR_BT_INSTALL_UTIL_UCS2
#endif

#ifndef EXCLUDE_CSR_BT_PAS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_UTIL_UCS2
#endif


#ifndef EXCLUDE_CSR_BT_SMLC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#ifndef EXCLUDE_CSR_BT_SMLC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif

#ifndef EXCLUDE_CSR_BT_SMLS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#ifndef EXCLUDE_CSR_BT_SMLS_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif



#ifndef EXCLUDE_CSR_BT_SYNCS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#ifndef EXCLUDE_CSR_BT_SYNCS_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif
 

#ifndef EXCLUDE_CSR_BT_SYNCC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_CHALLENGE
#define CSR_BT_INSTALL_OBEX_HEADER_AUTH_RESPONSE
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_UTIL_UCS2
#ifndef EXCLUDE_CSR_BT_SYNCC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_OBEX_HEADER_DESCRIPTION
#endif
#endif
 

#ifndef EXCLUDE_CSR_BT_MAPC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_CLI_SET_PATH
#define CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_CLI_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_UTIL_UCS2
#endif


#ifndef EXCLUDE_CSR_BT_MAPS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_CONTEXT_ID
#define CSR_BT_INSTALL_OBEX_SRV_GET
#define CSR_BT_INSTALL_OBEX_SRV_SET_PATH
#define CSR_BT_INSTALL_OBEX_SRV_HEADER_TARGET_WHO_CID
#define CSR_BT_INSTALL_OBEX_HEADER_APP_PARAMS
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#define CSR_BT_INSTALL_UTIL_UCS2
#endif
/* End of OBEX profiles */


#ifndef EXCLUDE_CSR_BT_HCRP_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_HIDD_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#define INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_HIDH_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_SC_ENCRYPTION
#define CSR_BT_INSTALL_CM_WRITE_LINK_SUPERVISION_TIMEOUT
#define INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif
 

#ifndef EXCLUDE_CSR_BT_JSR82_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#define CSR_BT_INSTALL_SC_AUTHENTICATE
#define CSR_BT_INSTALL_SC_ENCRYPTION
/* CM API functions */
#define CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#define CSR_BT_INSTALL_CM_WRITE_COD
#define CSR_BT_INSTALL_CM_READ_COD
#define CSR_BT_INSTALL_CM_READ_SCAN_EANBLE
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#define CSR_BT_INSTALL_CM_PRI_IAC
#define CSR_BT_INSTALL_CM_PRI_SDC
#define CSR_BT_INSTALL_CM_PRI_CONNECT_EXT
#endif


#ifndef EXCLUDE_CSR_BT_SAPC_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_SAPS_MODULE 
#define CSR_BT_INSTALL_RFC_MODULE
#endif



#ifndef EXCLUDE_CSR_BT_SPP_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#ifndef EXCLUDE_CSR_BT_SPP_MODULE_OPTIONAL
#ifdef CSR_USE_BLUECORE_CHIP
#define CSR_BT_INSTALL_SPP_EXTENDED
#endif
#endif
#endif

#ifndef EXCLUDE_CSR_BT_GNSS_CLIENT_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#endif

#ifndef EXCLUDE_CSR_BT_GNSS_SERVER_MODULE
#define CSR_BT_INSTALL_RFC_MODULE
#endif

#ifndef EXCLUDE_CSR_BT_PHDC_AG_MODULE 
#define CSR_BT_INSTALL_MDER_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_PHDC_MGR_MODULE 
#define CSR_BT_INSTALL_MDER_MODULE
#endif

#ifndef EXCLUDE_CSR_BT_HDP_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#define INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif


#ifndef EXCLUDE_CSR_BT_MCAP_MODULE 
#define CSR_BT_INSTALL_L2CAP_MODULE
#else
#define EXCLUDE_CSR_BT_MCAP_PRIVATE_MODULE 
#endif


#ifndef EXCLUDE_CSR_BT_BSL_MODULE
#define INSTALL_PAN_MODULE
#define CSR_BT_INSTALL_BSL_MODULE
#endif

#ifndef EXCLUDE_CSR_BT_SC_MODULE_OPTIONAL
#define CSR_BT_INSTALL_SC_AUTHENTICATE
#define CSR_BT_INSTALL_SC_ENCRYPTION
#define CSR_BT_INSTALL_SC_OOB
#define CSR_BT_INSTALL_SC_DEBUG_MODE
#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_MODE
#define CSR_BT_INSTALL_SC_SECURITY_MODE
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define CSR_BT_INSTALL_SC_TRUST_LEVEL
#define CSR_BT_INSTALL_SC_CONFIG_MASK
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#endif

#if defined(CSR_BT_INSTALL_SC_DEBUG_MODE) || defined(CSR_BT_INSTALL_SC_CONFIG_MASK)
#define CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#endif

#ifdef CSR_BT_INSTALL_SC_OOB
#define CSR_BT_INSTALL_CM_OOB
#endif

#ifndef EXCLUDE_CSR_BT_SD_MODULE_OPTIONAL
#define CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define CSR_BT_INSTALL_SD_MEMORY_CONFIG
#define INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif

#ifndef EXCLUDE_CSR_BT_CM_MODULE_OPTIONAL
#define CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#define CSR_BT_INSTALL_CM_WRITE_LINK_SUPERVISION_TIMEOUT
#define CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#define CSR_BT_INSTALL_CM_GET_LINK_QUALITY
#define CSR_BT_INSTALL_CM_READ_RSSI
#define CSR_BT_INSTALL_CM_WRITE_COD
#define CSR_BT_INSTALL_CM_READ_COD
#define CSR_BT_INSTALL_CM_READ_SCAN_EANBLE
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#define CSR_BT_INSTALL_CM_CONNECTABLE
#define CSR_BT_INSTALL_CM_WRITE_PAGE_TO
#define CSR_BT_INSTALL_CM_WRITE_PAGE_SCAN
#define CSR_BT_INSTALL_CM_WRITE_INQUIRY_SCAN_TYPE
#define CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES
#define CSR_BT_INSTALL_CM_AFH
#define CSR_BT_INSTALL_CM_READ_CLOCK
#define CSR_BT_INSTALL_CM_LINK_POLICY
#define CSR_BT_INSTALL_CM_EIR_FLAGS
#define CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG
#define CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#define CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#define CSR_BT_INSTALL_CM_LOW_POWER_CONFIG_PUBLIC
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_INITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ACL_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_SYNCHRONOUS_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ROLE_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_MODE_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LSTO_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_CHANNEL_TYPE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_EXT_SYNC_CONNECTION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_FEATURES
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_REMOTE_VERSION
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_A2DP_BIT_RATE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_INQUIRY_PAGE_STATE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOW_ENERGY
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_ENCRYPT_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LOCAL_NAME_CHANGE
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_HIGH_PRIORITY_DATA
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_BLUECORE_DEINITIALIZED
#define CSR_BT_INSTALL_CM_EVENT_MASK_SUBSCRIBE_LE_OWN_ADDR_TYPE_CHANGE

/* CM_Private */
#define CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#define CSR_BT_INSTALL_CM_PRI_SDC
#define CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE
#define CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH
#define CSR_BT_INSTALL_CM_PRI_CONNECT_EXT
#define CSR_BT_INSTALL_CM_PRI_SCO_RENEGOTIATE
#define CSR_BT_INSTALL_CM_PRI_MODE_SETTINGS
#define CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#define CSR_BT_INSTALL_CM_PRI_L2CA_DATA_ABORT
#define CSR_BT_INSTALL_CM_PRI_SET_EVENT_FILTER_BDADDR
#define CSR_BT_INSTALL_CM_OOB
#define CSR_BT_INSTALL_CM_SC_MODE_CONFIG
#endif

#ifndef CSR_BT_INSTALL_CM_OOB
#define CSR_BT_EXCLUDE_SM_READ_LOCAL_OOB_DATA
#endif

#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#define EXCLUDE_CSR_BT_CM_READ_LOCAL_NAME_REQ
#define EXCLUDE_CSR_BT_CM_READ_LOCAL_NAME_CFM
#endif

#ifdef CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES
/* If this flag is set, the code needed by internal 
   CSR-applications will be included. */
#define CSR_BT_INSTALL_CM_WRITE_COD /* Used by GAP demo app */
#define CSR_BT_INSTALL_CM_PRI_CONNECT_EXT /* Used by RFC test demo app */

#ifdef CSR_BT_LE_ENABLE
#define CSR_BT_INSTALL_CM_READ_RSSI /* Used by GATT Proximity demo app */
#endif

#define CSR_BT_INSTALL_SD_SEARCH_CONFIG /* Used by PAN demo app */

/* Used by SC demo app */
#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define CSR_BT_INSTALL_SC_SECURITY_MODE
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_UTIL_UCS2

#endif /* CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES */

#ifdef CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES
/* If this flag is set, the code needed by internal
   CSR tests will be included. */

#define CSR_BT_INSTALL_CM_READ_SCAN_EANBLE /* Used by several tester/tester groups */
#define CSR_BT_INSTALL_CM_LINK_POLICY /* Used by 1 tester/tester test case but several CM module tests */
#define CSR_BT_INSTALL_CM_READ_CLOCK /* Used by 1 tester/tester test case and profile_managers_development/test_app/app_files/csr_bt_test_app_mcap.c */
#define CSR_BT_INSTALL_CM_ROLE_SWITCH_CONFIG /* Used by 1 tester/tester test case and 1 CM module test case */
#define CSR_BT_INSTALL_CM_PRI_ALWAYS_SUPPORT_MASTER_ROLE /* Used by a few cm tester/tester test cases and throughput */
#define CSR_BT_INSTALL_CM_PRI_CANCEL_RFC_EXTENDED_SEARCH /* Used by a few tester/tester test cases */
#define CSR_BT_INSTALL_CM_PRI_SDC /* Used by a few tester/tester test cases and 1 CM module test case */
#define CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB /* Used by a few tester/tester test cases */
#define CSR_BT_INSTALL_SC_SECURITY_MODE /* This is needed to run the sc-group in tester, since all test cases sends the request. */
#define CSR_BT_INSTALL_OPTIONAL_UTIL /* Used by more or less all tester/tester test cases */
#define CSR_BT_INSTALL_CM_READ_RSSI /* Used by the generic test step testCaseWaitAclClosedInd() */

/* Low risk */
#define CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define CSR_BT_INSTALL_SD_MEMORY_CONFIG

#define CSR_BT_INSTALL_HF_CONFIG_AUDIO
#define CSR_BT_INSTALL_HFG_CONFIG_AUDIO

#define CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_UTIL_UCS2

#else /* CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES */
/* Used for spec. test */
#define CSR_BT_EXCLUDE_HCI_CHANGE_CONN_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_HOLD_MODE

#endif /* CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES */

#ifndef EXCLUDE_CSR_BT_DUT_MODULE
#define CSR_BT_INSTALL_CM_DUT_MODE
#else
#define CSR_BT_EXCLUDE_HCI_ENABLE_DUT_MODE
#endif

#ifdef CSR_BT_INSTALL_SPP_EXTENDED
#define CSR_BT_INSTALL_128_BIT_SERVICE_SEARCH
#define CSR_BT_INSTALL_CM_PRI_SCO_RENEGOTIATE
#endif

/* Convert to low-level EXCLUDE_FLAG 
TODO: CSR_BT_BT_VERSION is defined in csr_bt_usr_config.h, but it cannot be included
      in this file, since it includes other headers, which depend on this file... 
      One solution would be to move the include of the file to the bottom of this file
#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_NAME
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_2P1
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_NAME
#endif
#endif
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_2P1
#define CSR_BT_EXCLUDE_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA
#endif
*/



/* ---------- Cross Profile dependent flags ---------- */
#ifdef CSR_BT_OBEX_GOEP_20_CAPABLE_PROFILE_ENABLED
#ifndef EXCLUDE_CSR_BT_L2CA_MODULE
#ifndef EXCLUDE_CSR_BT_GOEP_20_MODULE
/* Only do this if an OBEX 20 cabacle profile is enabled */
#define CSR_BT_INSTALL_L2CAP_MODULE 
#define CSR_BT_INSTALL_OBEX_GOEP_20
#define CSR_BT_INSTALL_CM_PRI_L2CA_UNREGISTER
#define CSR_BT_INSTALL_CM_PRI_L2CA_CONNECT_CONFTAB
#define CSR_BT_INSTALL_CM_PRI_L2CA_DATA_ABORT
#endif
#endif
#endif

#ifndef EXCLUDE_CSR_EXCEPTION_HANDLER_MODULE
#define CSR_BT_INSTALL_OBEX_ERROR_CHECK
#endif


/* ---------- Ensure we have backwards compatibility ---------- */
#ifndef EXCLUDE_CSR_BT_OPTIONAL_UTILS 
#define CSR_BT_INSTALL_UTIL_UCS2
#define CSR_BT_INSTALL_OPTIONAL_UTIL
#define CSR_BT_INSTALL_OBEX_UTIL_XML
#define CSR_BT_INSTALL_OBEX_UTIL_SET_SERVICE_HANDLE_RES
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_NON_CONNECTABLE
#define CSR_BT_INSTALL_OBEX_UTIL_SERV_PUT_GET_WITH_HEADER_EXT
#else
#if defined(EXCLUDE_CSR_BT_BSL_MODULE) && defined(EXCLUDE_CSR_BT_DUNC_MODULE) && !defined(CSR_BT_INSTALL_INTERNAL_TEST_DEPENDENCIES) && !defined(CSR_BT_INSTALL_INTERNAL_APP_DEPENDENCIES)
#define EXCLUDE_CSR_BT_UDP_MODULE
#define EXCLUDE_CSR_BT_LSL_MODULE
#define EXCLUDE_CSR_BT_IP_MODULE
#define EXCLUDE_CSR_BT_ICMP_MODULE
#define EXCLUDE_CSR_BT_DHCP_MODULE
#define EXCLUDE_CSR_BT_PPP_MODULE
#endif
#endif

/* ---------- Test functionality ---------- */
#ifndef EXCLUDE_CSR_BT_TPT_MODULE
#define CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
/* REQ SPP */
#endif

/* ---------- Resolve install-flags dependencies ---------- */
#ifdef CSR_BT_INSTALL_OBEX_CLI_GET
#define CSR_BT_INSTALL_OBEX_UTIL_BODY_OFFSET 
#endif

#ifndef INSTALL_CSR_BT_SD_SERVICE_RECORD_MODULE
#ifndef EXCLUDE_CSR_BT_SD_SERVICE_RECORD_MODULE
#define EXCLUDE_CSR_BT_SD_SERVICE_RECORD_MODULE
#endif
#endif

/* ---------- Convert install-flags to legacy exclude-flags ---------- */

#ifndef CSR_BT_INSTALL_L2CAP_MODULE
#undef EXCLUDE_CSR_BT_L2CA_MODULE
#define EXCLUDE_CSR_BT_L2CA_MODULE
#endif

#ifndef CSR_BT_INSTALL_RFC_MODULE
#undef EXCLUDE_CSR_BT_RFC_MODULE
#define EXCLUDE_CSR_BT_RFC_MODULE
#endif

#ifndef CSR_BT_INSTALL_BSL_MODULE
#undef EXCLUDE_CSR_BT_BNEP_MODULE 
#define EXCLUDE_CSR_BT_BNEP_MODULE 
#endif

#ifndef CSR_BT_INSTALL_MDER_MODULE
#undef EXCLUDE_CSR_BT_MDER_MODULE 
#define EXCLUDE_CSR_BT_MDER_MODULE 
#endif

/* DM_SYNC (SCO) mandatory settings */
#ifndef CSR_BT_INSTALL_SCO_MODULE
#undef EXCLUDE_CSR_BT_SCO_MODULE
#define EXCLUDE_CSR_BT_SCO_MODULE
#undef INSTALL_DM_SYNC_MODULE
#undef CSR_BT_MAX_NUM_SCO_CONNS /* This will not work, as csr_bt_user_config.h is included after this file is included */
#define CSR_BT_EXCLUDE_SYNC_CONNECT
#define CSR_BT_EXCLUDE_SYNC_DISCONNECT
#define CSR_BT_EXCLUDE_SYNC_REGISTER
#define CSR_BT_EXCLUDE_SYNC_RENEGOTIATE
#define CSR_BT_EXCLUDE_SYNC_UNREGISTER
#else
#define INSTALL_DM_SYNC_MODULE
#endif

/* DM mandatory settings */
#ifndef INSTALL_BUILD_FOR_HOST_DM_ACL_CON_HANDLE_IND
#define INSTALL_BUILD_FOR_HOST_DM_ACL_CON_HANDLE_IND
#endif

#ifndef INSTALL_BUILD_FOR_HOST_DM_ACL_CON_START_IND
#define INSTALL_BUILD_FOR_HOST_DM_ACL_CON_START_IND
#endif

#ifndef BUILD_FOR_HOST_OLD_LINK_KEY_API
#define BUILD_FOR_HOST_OLD_LINK_KEY_API
#endif

/* RFCOMM mandatory settings */
#ifndef EXCLUDE_CSR_BT_RFC_MODULE
#undef INSTALL_RFCOMM_MODULE
#define INSTALL_RFCOMM_MODULE
#define RFCOMM_MULTI_THREAD
#endif /* EXCLUDE_CSR_BT_RFC_MODULE */


#ifdef INSTALL_IBFP
#undef CSR_IBFP_H4I_SUPPORT
#define CSR_IBFP_H4I_SUPPORT

#undef CSR_H4I_ENABLE_PATCH
#define CSR_H4I_ENABLE_PATCH

#undef CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE
#define CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE

#undef INSTALL_BUILD_FOR_HOST_NO_OVERRIDE_HCI_CMD_FC
#define INSTALL_BUILD_FOR_HOST_NO_OVERRIDE_HCI_CMD_FC

#ifdef CSR_BT_LE_ENABLE
#undef SUPPORT_SEPARATE_LE_BUFFERS 
#define SUPPORT_SEPARATE_LE_BUFFERS 
#endif
#endif

#ifdef CSR_USE_QCA_CHIP
#ifdef CSR_BT_LE_ENABLE
#undef SUPPORT_SEPARATE_LE_BUFFERS 
#define SUPPORT_SEPARATE_LE_BUFFERS 
#endif
#endif

/* Exclude converter functions for specific primitives */
#ifndef CSR_BT_INSTALL_SC_SET_EVENT_MASK
#define EXCLUDE_CSR_BT_SC_SET_EVENT_MASK_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_SET_IO_CAPABILITY
#define EXCLUDE_CSR_BT_SC_SET_IO_CAPABILITY_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_SET_AUTH_REQUIREMENTS
#define EXCLUDE_CSR_BT_SC_SET_AUTH_REQUIREMENTS_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_MODE
#define EXCLUDE_CSR_BT_SC_MODE_REQ
#define EXCLUDE_CSR_BT_SC_MODE_IND
#endif

#ifndef CSR_BT_INSTALL_SC_LE_KEY_DISTRIBUTION
#define EXCLUDE_CSR_BT_SC_LE_KEY_DISTRIBUTION_REQ
#endif

#ifndef CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#define CSR_BT_INSTALL_SC_EVENT_MASK_SUBSCRIBE_ADDRESS_MAPPED_IND
#endif

#ifndef CSR_BT_INSTALL_AV_SET_QOS_INTERVAL
#define EXCLUDE_CSR_BT_AV_SET_QOS_INTERVAL_REQ
#endif

#ifndef CSR_BT_INSTALL_SD_SEARCH_CONFIG
#define EXCLUDE_CSR_BT_SD_SEARCH_CONFIG_REQ
#define EXCLUDE_CSR_BT_SD_SEARCH_CONFIG_CFM
#endif

#ifndef CSR_BT_INSTALL_CM_WRITE_VOICE_SETTINGS
#define EXCLUDE_CSR_BT_CM_WRITE_VOICE_SETTINGS_REQ
#define EXCLUDE_CSR_BT_CM_WRITE_VOICE_SETTINGS_CFM
#endif

#ifndef CSR_BT_INSTALL_HF_CONFIG_AUDIO
#define EXCLUDE_CSR_BT_HF_CONFIG_AUDIO_REQ
#define EXCLUDE_CSR_BT_HF_CONFIG_AUDIO_CFM
#endif

#ifndef CSR_BT_INSTALL_HFG_CONFIG_AUDIO
#define EXCLUDE_CSR_BT_HFG_CONFIG_AUDIO_REQ
#endif
#ifndef CSR_BT_INSTALL_HFG_CONFIG_SINGLE_ATCMD
#define EXCLUDE_CSR_BT_HFG_CONFIG_SINGLE_ATCMD_REQ
#define EXCLUDE_CSR_BT_HFG_CONFIG_SINGLE_ATCMD_CFM
#endif
#ifndef CSR_BT_INSTALL_HFG_CONFIG_ATCMD_HANDLING
#define EXCLUDE_CSR_BT_HFG_CONFIG_ATCMD_HANDLING_REQ
#define EXCLUDE_CSR_BT_HFG_CONFIG_ATCMD_HANDLING_CFM
#endif

#ifndef CSR_BT_INSTALL_GATT_PARAM_CONNECTION
#define EXCLUDE_CSR_BT_GATT_PARAM_CONNECTION_REQ
#define EXCLUDE_CSR_BT_GATT_PARAM_CONNECTION_CFM
#endif

#ifndef CSR_BT_INSTALL_AVRCP_CT_13_AND_HIGHER
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_DISP_CHARSET_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_REGISTER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_ID_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_ID_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_CURRENT_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_PLAY_STATUS_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_RES
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_FOLDER_ITEMS_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_PLAY_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SEARCH_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_CHANGE_PATH_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_VOLUME_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_BROWSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_ADD_TO_NOW_PLAYING_REQ
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_BATTERY_STATUS_REQ

#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_DISP_CHARSET_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_REGISTER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_PLAY_STATUS_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_ID_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_ID_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_CURRENT_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_FOLDER_ITEMS_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_PLAY_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SEARCH_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_CHANGE_PATH_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_VOLUME_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_BROWSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_ADD_TO_NOW_PLAYING_CFM
#define EXCLUDE_CSR_BT_AVRCP_CT_INFORM_BATTERY_STATUS_CFM

#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_ATT_TXT_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_VAL_TXT_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_PAS_SET_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_UIDS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_VOLUME_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_BATTERY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_PLAYBACK_POS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_SYSTEM_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_CHANGED_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_END_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_TRACK_START_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_PLAYBACK_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_AVAILABLE_PLAYERS_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_NOTI_NOW_PLAYING_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_GET_ATTRIBUTES_IND
#define EXCLUDE_CSR_BT_AVRCP_CT_SET_ADDRESSED_PLAYER_IND
#endif
#ifndef CSR_BT_INSTALL_AVRCP_TG_13_AND_HIGHER
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_REQ
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PLAY_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SEARCH_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_CHANGE_PATH_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_CURRENT_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_VOLUME_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_FOLDER_ITEMS_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_ATTRIBUTES_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_PLAY_STATUS_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_BROWSED_PLAYER_RES
#define EXCLUDE_CSR_BT_AVRCP_TG_ADD_TO_NOW_PLAYING_RES

#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_CFM
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PLAY_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SEARCH_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_CURRENT_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_CHANGE_PATH_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_VOLUME_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_FOLDER_ITEMS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_PLAY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_ADDRESSED_PLAYER_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_SET_BROWSED_PLAYER_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_GET_ATTRIBUTES_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_ADD_TO_NOW_PLAYING_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_INFORM_DISP_CHARSET_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_INFORM_BATTERY_STATUS_IND
#define EXCLUDE_CSR_BT_AVRCP_TG_NOTI_CFM
#define EXCLUDE_CSR_BT_AVRCP_TG_PAS_SET_CFM
#endif

#ifndef INSTALL_ULP
#define CSR_BT_EXCLUDE_BLE_ACCEPT_CONNECTION_PAR_UPDATE
#define CSR_BT_EXCLUDE_BLE_UPDATE_CONNECTION_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_CLEAR_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_CREATE_CONNECTION_CANCEL
#define CSR_BT_EXCLUDE_HCI_ULP_ENCRYPT
#define CSR_BT_EXCLUDE_HCI_ULP_RAND
#define CSR_BT_EXCLUDE_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER
#define CSR_BT_EXCLUDE_HCI_ULP_READ_CHANNEL_MAP
#define CSR_BT_EXCLUDE_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_REMOTE_USED_FEATURES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_SUPPORTED_STATES
#define CSR_BT_EXCLUDE_HCI_ULP_READ_WHITE_LIST_SIZE
#define CSR_BT_EXCLUDE_HCI_ULP_RECEIVER_TEST
#define CSR_BT_EXCLUDE_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISE_ENABLE
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_DATA
#define CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_EVENT_MASK
#define CSR_BT_EXCLUDE_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION
#define CSR_BT_EXCLUDE_HCI_ULP_SET_RANDOM_ADDRESS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_ENABLE
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_PARAMETERS
#define CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_RESPONSE_DATA
#define CSR_BT_EXCLUDE_HCI_ULP_TEST_END
#define CSR_BT_EXCLUDE_HCI_ULP_TRANSMITTER_TEST
#endif

#ifndef INSTALL_AMP_SUPPORT
/* AMP only signals */
#define CSR_BT_EXCLUDE_AMPM_CONNECT
#define CSR_BT_EXCLUDE_AMPM_CONNECT_CHANNEL
#define CSR_BT_EXCLUDE_AMPM_DISCONNECT
#define CSR_BT_EXCLUDE_AMPM_DISCONNECT_CHANNEL
#define CSR_BT_EXCLUDE_AMPM_NUMBER_COMPLETED_DATA_BLOCKS
#define CSR_BT_EXCLUDE_AMPM_READ_BD_ADDR
#define CSR_BT_EXCLUDE_AMPM_READ_DATA_BLOCK_SIZE
#define CSR_BT_EXCLUDE_AMPM_REGISTER
#define CSR_BT_EXCLUDE_AMPM_VERIFY_PHYSICAL_LINK
/* Signals only used for AMP */
#define CSR_BT_EXCLUDE_DATA_FROM_HCI
#endif

#ifndef INSTALL_BD_ADDR_BLACK_LIST_SUPPORT
#define CSR_BT_EXCLUDE_HANDLE_DEVICE_BLACK_LIST
#endif

#ifndef CSR_BT_INSTALL_CM_GET_LINK_QUALITY
#define CSR_BT_EXCLUDE_HCI_GET_LINK_QUALITY
#endif

#ifndef CSR_BT_INSTALL_CM_AFH
#define CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_CLASS_M
#define CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_MAP
#define CSR_BT_EXCLUDE_HCI_SET_AFH_CHANNEL_CLASS
#define CSR_BT_EXCLUDE_HCI_WRITE_AFH_CHANNEL_CLASS_M
#endif

#ifndef CSR_BT_INSTALL_CM_READ_COD
#define CSR_BT_EXCLUDE_HCI_READ_CLASS_OF_DEVICE
#endif

#ifndef CSR_BT_INSTALL_CM_READ_CLOCK
#define CSR_BT_EXCLUDE_HCI_READ_CLOCK
#endif

#ifndef CSR_BT_INSTALL_CM_PRI_IAC
#define CSR_BT_EXCLUDE_HCI_READ_CURRENT_IAC_LAP
#define CSR_BT_EXCLUDE_HCI_READ_NUM_SUPPORTED_IAC
#endif

/* This requiers the csr_bt_usr_config.h to be included, which destrois the auto-gen system...
#if CSR_BT_BT_VERSION < CSR_BT_BLUETOOTH_VERSION_3P0
#define CSR_BT_EXCLUDE_HCI_READ_ENCRYPTION_KEY_SIZE 
#define CSR_BT_EXCLUDE_SM_IO_CAPABILITY_REQUEST
#define CSR_BT_EXCLUDE_SM_IO_CAPABILITY_REQUEST_NEG
#define CSR_BT_EXCLUDE_SM_SEND_KEYPRESS_NOTIFICATION
#define CSR_BT_EXCLUDE_SM_USER_CONFIRMATION_REQUEST
#define CSR_BT_EXCLUDE_SM_USER_CONFIRMATION_REQUEST_NEG
#define CSR_BT_EXCLUDE_SM_USER_PASSKEY_REQUEST
#define CSR_BT_EXCLUDE_SM_USER_PASSKEY_REQUEST_NEG
#endif
*/
#ifndef CSR_BT_INSTALL_CM_READ_FAILED_CONTACT_COUNTER
#define CSR_BT_EXCLUDE_HCI_READ_FAILED_CONTACT_COUNT
#endif

#ifndef CSR_BT_INSTALL_CM_READ_LOCAL_EXT_FEATURES
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_EXT_FEATURES
#endif

#ifndef CSR_BT_INSTALL_CM_READ_RSSI
#define CSR_BT_EXCLUDE_HCI_READ_RSSI
#endif

#ifndef CSR_BT_INSTALL_CM_READ_SCAN_EANBLE
#define CSR_BT_EXCLUDE_HCI_READ_SCAN_ENABLE
#endif

#ifndef CSR_BT_INSTALL_CM_READ_TX_POWER_LEVEL
#define CSR_BT_EXCLUDE_HCI_READ_TX_POWER_LEVEL
#endif

#ifndef CSR_BT_INSTALL_L2CAP_MODULE
#define CSR_BT_EXCLUDE_HCI_WRITE_AUTO_FLUSH_TIMEOUT
#endif

#ifndef CSR_BT_INSTALL_CM_PRI_IAC
#define CSR_BT_EXCLUDE_HCI_WRITE_CURRENT_IAC_LAP
#endif

#ifndef CSR_BT_INSTALL_CM_SWITCH_ROLE_PUBLIC
#define CSR_BT_EXCLUDE_LP_WRITE_ALWAYS_MASTER_DEVICES
#endif

#ifndef CSR_BT_INSTALL_SC_AUTHENTICATE
#define CSR_BT_EXCLUDE_SM_AUTHENTICATE
#endif

#ifndef CSR_BT_INSTALL_SC_ENCRYPTION
#define CSR_BT_EXCLUDE_SM_ENCRYPT
#endif

/* Unused DM lib functions - Typically located in dm_hci_int_cc_gen.c and lib-finctions*/
#define CSR_BT_EXCLUDE_HCI_CHANGE_ACL_CONN_PKT_TYPE
#define CSR_BT_EXCLUDE_HCI_CREATE_NEW_UNIT_KEY
#define CSR_BT_EXCLUDE_HCI_EXIT_PERIODIC_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_FLUSH
#define CSR_BT_EXCLUDE_HCI_PERIODIC_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_READ_AUTH_ENABLE
#define CSR_BT_EXCLUDE_HCI_READ_AUTO_FLUSH_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_READ_CONN_ACCEPT_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_READ_COUNTRY_CODE
#define CSR_BT_EXCLUDE_HCI_READ_DEFAULT_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_READ_ENC_MODE
#define CSR_BT_EXCLUDE_HCI_READ_HOLD_MODE_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRY_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_INQUIRYSCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_LINK_SUPERV_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_READ_LMP_HANDLE
#define CSR_BT_EXCLUDE_HCI_READ_NUM_BCAST_RETXS
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_MODE
#define CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_PERIOD_MODE
#define CSR_BT_EXCLUDE_HCI_READ_PIN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_SCO_FLOW_CON_ENABLE
#define CSR_BT_EXCLUDE_HCI_READ_STORED_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_READ_VOICE_SETTING
#define CSR_BT_EXCLUDE_HCI_RESET_FAILED_CONTACT_COUNT
#define CSR_BT_EXCLUDE_HCI_WRITE_CONN_ACCEPT_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_WRITE_HOLD_MODE_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_WRITE_NUM_BCAST_RETXS
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_MODE
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_PERIOD_MODE
#define CSR_BT_EXCLUDE_HCI_WRITE_PIN_TYPE
#define CSR_BT_EXCLUDE_HCI_WRITE_SCO_FLOW_CON_ENABLE
#define CSR_BT_EXCLUDE_HCI_WRITE_STORED_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_READ_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_READ_PAGE_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_READ_PAGE_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_SET_EVENT_MASK /* lib-function never reffered, but HCI-command used in core-stack */
#define CSR_BT_EXCLUDE_SM_DATA_SIGN 
#define CSR_BT_EXCLUDE_SM_GENERATE_NONRESOLVABLE_PRIVATE_ADDRESS
#define CSR_BT_EXCLUDE_SM_READ_DEVICE

#ifdef CSR_BT_INSTALL_CHANGE_ACL_PACKET_TYPE
#undef CSR_BT_EXCLUDE_HCI_CHANGE_ACL_CONN_PKT_TYPE
#endif



/* dm-excludes - These are always used:
#define CSR_BT_EXCLUDE_ACL_CLOSE
#define CSR_BT_EXCLUDE_ACL_OPEN
#define CSR_BT_EXCLUDE_AM_REGISTER
#define CSR_BT_EXCLUDE_CLEAR_PARAM_CACHE
#define CSR_BT_EXCLUDE_HCI_CHANGE_LOCAL_NAME
#define CSR_BT_EXCLUDE_HCI_CREATE_CONNECTION_CANCEL
#define CSR_BT_EXCLUDE_HCI_DELETE_STORED_LINK_KEY
#define CSR_BT_EXCLUDE_HCI_EXIT_SNIFF_MODE
#define CSR_BT_EXCLUDE_HCI_INQUIRY
#define CSR_BT_EXCLUDE_HCI_INQUIRY_CANCEL
#define CSR_BT_EXCLUDE_HCI_QOS_SETUP
#define CSR_BT_EXCLUDE_HCI_READ_BD_ADDR
#define CSR_BT_EXCLUDE_HCI_READ_CLOCK_OFFSET
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_SUPP_FEATURES
#define CSR_BT_EXCLUDE_HCI_READ_LOCAL_VER_INFO
#define CSR_BT_EXCLUDE_HCI_READ_REMOTE_EXT_FEATURES
#define CSR_BT_EXCLUDE_HCI_READ_REMOTE_SUPP_FEATURES
#define CSR_BT_EXCLUDE_HCI_READ_REMOTE_VER_INFO
#define CSR_BT_EXCLUDE_HCI_REMOTE_NAME_REQUEST
#define CSR_BT_EXCLUDE_HCI_REMOTE_NAME_REQ_CANCEL
#define CSR_BT_EXCLUDE_HCI_ROLE_DISCOVERY
#define CSR_BT_EXCLUDE_HCI_SET_EVENT_FILTER
#define CSR_BT_EXCLUDE_HCI_SNIFF_MODE
#define CSR_BT_EXCLUDE_HCI_SNIFF_SUB_RATE
#define CSR_BT_EXCLUDE_HCI_SWITCH_ROLE
#define CSR_BT_EXCLUDE_HCI_WRITE_CLASS_OF_DEVICE
#define CSR_BT_EXCLUDE_HCI_WRITE_INQUIRYSCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_MODE
#define CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL
#define CSR_BT_EXCLUDE_HCI_WRITE_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_WRITE_LINK_SUPERV_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_ACTIVITY
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGE_SCAN_TYPE
#define CSR_BT_EXCLUDE_HCI_WRITE_PAGE_TIMEOUT
#define CSR_BT_EXCLUDE_HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS
#define CSR_BT_EXCLUDE_HCI_WRITE_SCAN_ENABLE
#define CSR_BT_EXCLUDE_LINK_KEY_REQUEST
#define CSR_BT_EXCLUDE_LP_WRITE_ROLESWITCH_POLICY
#define CSR_BT_EXCLUDE_SET_BT_VERSION
#define CSR_BT_EXCLUDE_SET_DEFAULT_LINK_POLICY
#define CSR_BT_EXCLUDE_SM_AUTHORISE
#define CSR_BT_EXCLUDE_SM_BONDING
#define CSR_BT_EXCLUDE_SM_BONDING_CANCEL
#define CSR_BT_EXCLUDE_SM_INIT
#define CSR_BT_EXCLUDE_SM_KEY_REQUEST
#define CSR_BT_EXCLUDE_SM_KEY_REQUEST_NEG
#define CSR_BT_EXCLUDE_SM_PIN_REQUEST
#define CSR_BT_EXCLUDE_SM_REGISTER
#define CSR_BT_EXCLUDE_SM_REGISTER_OUTGOING
#define CSR_BT_EXCLUDE_SM_REMOVE_DEVICE
#define CSR_BT_EXCLUDE_SM_UNREGISTER
#define CSR_BT_EXCLUDE_SM_UNREGISTER_OUTGOING
#define CSR_BT_EXCLUDE_WRITE_CACHED_CLOCK_OFFSET
#define CSR_BT_EXCLUDE_WRITE_CACHED_PAGE_MODE
#define CSR_BT_EXCLUDE_SM_CONFIGURE_LOCAL_ADDRESS

*/

#ifdef __cplusplus
}
#endif


#endif
