/**
 * dw9716_actuator.h
 *
 * DESCRIPTION
 *  Auto-Generated by Actuator tool.
 *
 * Copyright (c) 2014 Qualcomm Technologies, Inc. All Rights Reserved.
 *   Qualcomm Technologies Proprietary and Confidential.
 */
  {
    .actuator_params =
    {
      .module_name = "abico",
      .actuator_name = "dw9716",
      .i2c_addr = 0x18,
      .i2c_data_type = CAMERA_I2C_BYTE_DATA,
      .i2c_addr_type = CAMERA_I2C_BYTE_ADDR,
      .act_type = ACTUATOR_TYPE_VCM,
      .data_size = 10,
      .reg_tbl =
      {
        .reg_tbl_size = 1,
        .reg_params =
        {
          {
            .reg_write_type = ACTUATOR_WRITE_DAC,
            .hw_mask = 0x0000000F,
            .reg_addr = 0xFFFF,
            .hw_shift = 0,
            .data_shift = 4,
          },
        },
      },
      .init_setting_size = 0,
      .init_settings =
      {

      },
    }, /* actuator_params */

    .actuator_tuned_params =
    {
      .scenario_size =
      {
        2, /* MOVE_NEAR */
        3, /* MOVE_FAR */
      },
      .ringing_scenario =
      {
        /* MOVE_NEAR */
        {
          40,
          370,
        },
        /* MOVE_FAR */
        {
          80,
          220,
          370,
        },
      },
      .initial_code = 88,
      .region_size = 1,
      .region_params =
      {
        {
          .step_bound =
          {
            373, /* Macro step boundary*/
            0, /* Infinity step boundary*/
          },
          .code_per_step = 1,
        },
      },
      .damping =
      {
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 4500,
                .hw_params = 0xF,
              },
            },
          },
          /* Scenario 1 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 0,
                .hw_params = 0xB,
              },
            },
          },
        },
        /* damping[MOVE_NEAR] */
        {
          /* Scenario 0 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 4500,
                .hw_params = 0xF,
              },
            },
          },
          /* Scenario 1 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 4500,
                .hw_params = 0xB,
              },
            },
          },
          /* Scenario 2 */
          {
            .ringing_params =
            {
              /* Region 0 */
              {
                .damping_step = 0x1FF,
                .damping_delay = 15000,
                .hw_params = 0xB,
              },
            },
          },
        },
      },
    }, /* actuator_tuned_params */
  },
